-- 插入预设系统资源
-- 注意：url字段使用占位符，实际使用时需要通过管理后台上传真实图片

-- ========== 头像类别 (Avatar) - 至少20个 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
-- 现实风格头像
('温柔少女', 'placeholder://avatar/gentle_girl.jpg', 'avatar', '温柔可爱的少女头像，适合日常场景', 'A gentle and cute girl portrait, soft features, warm smile, natural lighting, realistic style, high quality, detailed facial features, peaceful expression, modern clothing, studio portrait photography', '温柔,少女,日常,现实'),
('阳光少年', 'placeholder://avatar/sunny_boy.jpg', 'avatar', '阳光开朗的少年头像，充满活力', 'A sunny and cheerful boy portrait, bright smile, energetic expression, natural outdoor lighting, realistic style, high quality, detailed facial features, modern casual clothing, vibrant colors, portrait photography', '阳光,少年,活力,现实'),
('成熟女性', 'placeholder://avatar/mature_woman.jpg', 'avatar', '成熟优雅的女性头像，职场风格', 'A mature and elegant woman portrait, professional appearance, confident expression, soft studio lighting, realistic style, high quality, detailed facial features, business attire, sophisticated look, portrait photography', '成熟,女性,职场,现实'),
('商务男士', 'placeholder://avatar/business_man.jpg', 'avatar', '商务精英男士头像，正式场合', 'A professional business man portrait, formal attire, confident expression, professional lighting, realistic style, high quality, detailed facial features, suit and tie, serious expression, corporate portrait photography', '商务,男士,正式,现实'),
('文艺青年', 'placeholder://avatar/artistic_youth.jpg', 'avatar', '文艺范青年头像，艺术气息', 'An artistic youth portrait, creative style, thoughtful expression, soft natural lighting, realistic style, high quality, detailed facial features, casual artistic clothing, bohemian style, artistic portrait photography', '文艺,青年,艺术,现实'),

-- 古风风格头像
('古风美人', 'placeholder://avatar/ancient_beauty.jpg', 'avatar', '古典美人头像，传统服饰', 'A beautiful ancient Chinese woman portrait, traditional hanfu clothing, elegant hairstyle, delicate features, soft traditional lighting, Chinese painting style, high quality, detailed facial features, classical beauty, traditional portrait art', '古风,美人,传统,历史'),
('江湖侠客', 'placeholder://avatar/martial_hero.jpg', 'avatar', '江湖侠客头像，武侠风格', 'A martial arts hero portrait, traditional Chinese warrior clothing, heroic expression, dynamic lighting, Chinese ink painting style, high quality, detailed facial features, sword and weapon, martial arts style, traditional Chinese art', '江湖,侠客,武侠,历史'),
('文人墨客', 'placeholder://avatar/scholar.jpg', 'avatar', '古代文人头像，书卷气息', 'An ancient Chinese scholar portrait, traditional scholar clothing, scholarly appearance, gentle lighting, Chinese literati painting style, high quality, detailed facial features, holding brush or book, intellectual expression, traditional Chinese art', '文人,墨客,书卷,历史'),

-- 奇幻风格头像
('魔法少女', 'placeholder://avatar/magic_girl.jpg', 'avatar', '魔法少女头像，奇幻风格', 'A magical girl portrait, fantasy style, sparkling magical effects, ethereal lighting, anime-inspired style, high quality, detailed facial features, magical costume, glowing eyes, fantasy art style, vibrant colors', '魔法,少女,奇幻,虚幻'),
('精灵王子', 'placeholder://avatar/elf_prince.jpg', 'avatar', '精灵王子头像，神秘优雅', 'An elf prince portrait, fantasy style, pointed ears, ethereal beauty, mystical lighting, fantasy art style, high quality, detailed facial features, elegant elven clothing, magical aura, fantasy character art', '精灵,王子,神秘,虚幻'),
('赛博朋克少女', 'placeholder://avatar/cyberpunk_girl.jpg', 'avatar', '赛博朋克风格少女头像，未来感', 'A cyberpunk girl portrait, futuristic style, neon lighting, cybernetic enhancements, dark urban atmosphere, cyberpunk art style, high quality, detailed facial features, futuristic clothing, neon colors, sci-fi portrait', '赛博朋克,少女,未来,虚幻'),
('机甲战士', 'placeholder://avatar/mecha_warrior.jpg', 'avatar', '机甲战士头像，科幻风格', 'A mecha warrior portrait, sci-fi style, mechanical armor, high-tech appearance, dramatic lighting, sci-fi art style, high quality, detailed mechanical features, futuristic combat suit, technological details, science fiction art', '机甲,战士,科幻,虚幻'),

-- 二次元风格头像
('日系萌妹', 'placeholder://avatar/kawaii_girl.jpg', 'avatar', '日系萌妹头像，可爱风格', 'A kawaii Japanese girl portrait, anime style, cute expression, bright colors, soft lighting, anime art style, high quality, detailed anime facial features, kawaii clothing, adorable expression, Japanese anime art', '日系,萌妹,可爱,二次元'),
('御姐风格', 'placeholder://avatar/onee_san.jpg', 'avatar', '御姐风格头像，成熟魅力', 'A mature onee-san portrait, anime style, confident expression, elegant appearance, soft lighting, anime art style, high quality, detailed anime facial features, sophisticated clothing, mature beauty, anime character art', '御姐,成熟,魅力,二次元'),
('少年英雄', 'placeholder://avatar/shounen_hero.jpg', 'avatar', '少年英雄头像，热血风格', 'A shounen hero portrait, anime style, determined expression, dynamic pose, dramatic lighting, anime art style, high quality, detailed anime facial features, hero costume, energetic expression, shounen anime art', '少年,英雄,热血,二次元'),

-- 其他风格头像
('神秘面具', 'placeholder://avatar/mysterious_mask.jpg', 'avatar', '神秘面具头像，神秘风格', 'A mysterious masked portrait, enigmatic style, ornate mask, mysterious atmosphere, dramatic shadows, fantasy art style, high quality, detailed mask design, elegant clothing, mysterious aura, gothic art style', '神秘,面具,暗黑,通用'),
('童话公主', 'placeholder://avatar/fairy_princess.jpg', 'avatar', '童话公主头像，梦幻风格', 'A fairy tale princess portrait, fantasy style, elegant dress, crown, magical atmosphere, soft dreamy lighting, fantasy art style, high quality, detailed facial features, princess costume, enchanting expression, fairy tale art', '童话,公主,梦幻,通用'),
('摇滚歌手', 'placeholder://avatar/rock_star.jpg', 'avatar', '摇滚歌手头像，个性风格', 'A rock star portrait, edgy style, bold expression, dramatic lighting, high contrast, realistic style, high quality, detailed facial features, rock music clothing, rebellious look, music portrait photography', '摇滚,歌手,个性,通用'),
('瑜伽导师', 'placeholder://avatar/yoga_teacher.jpg', 'avatar', '瑜伽导师头像，平和风格', 'A yoga teacher portrait, peaceful style, serene expression, natural lighting, zen atmosphere, realistic style, high quality, detailed facial features, yoga clothing, calm expression, wellness portrait photography', '瑜伽,导师,平和,通用'),
('咖啡师', 'placeholder://avatar/barista.jpg', 'avatar', '咖啡师头像，专业风格', 'A barista portrait, professional style, focused expression, warm cafe lighting, cozy atmosphere, realistic style, high quality, detailed facial features, cafe uniform, friendly expression, professional portrait photography', '咖啡师,专业,温暖,通用'),
('旅行者', 'placeholder://avatar/traveler.jpg', 'avatar', '旅行者头像，自由风格', 'A traveler portrait, adventurous style, free-spirited expression, natural outdoor lighting, travel atmosphere, realistic style, high quality, detailed facial features, travel clothing, wanderlust expression, travel photography', '旅行者,自由,冒险,通用');

-- ========== 时代类别 (Era) - 至少20个 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
-- 现实时代
('我的大学', 'placeholder://era/my_university.jpg', 'era', '大学时代，青春校园生活', 'A university campus scene, modern buildings, students walking, green lawns, academic atmosphere, realistic style, high quality, detailed architecture, vibrant campus life, educational environment, contemporary photography, warm daylight', '大学,校园,青春,现实'),
('我的中学', 'placeholder://era/my_high_school.jpg', 'era', '中学时代，青涩年华', 'A high school scene, school building, students in uniform, playground, youthful atmosphere, realistic style, high quality, detailed school environment, teenage life, educational setting, contemporary photography, bright daylight', '中学,校园,青春,现实'),
('我的工作', 'placeholder://era/my_workplace.jpg', 'era', '职场时代，工作环境', 'A modern office workplace, professional environment, business setting, contemporary architecture, work atmosphere, realistic style, high quality, detailed office interior, professional setting, corporate environment, modern photography, office lighting', '工作,职场,专业,现实'),
('我的童年', 'placeholder://era/my_childhood.jpg', 'era', '童年时代，纯真回忆', 'A childhood scene, playground, toys, children playing, nostalgic atmosphere, realistic style, high quality, detailed childhood environment, innocent memories, playful setting, nostalgic photography, warm golden hour', '童年,纯真,回忆,现实'),
('我的故乡', 'placeholder://era/my_hometown.jpg', 'era', '故乡时代，家乡记忆', 'A hometown scene, traditional architecture, local streets, hometown atmosphere, nostalgic feeling, realistic style, high quality, detailed hometown environment, familiar places, local culture, nostalgic photography, warm lighting', '故乡,家乡,记忆,现实'),

-- 历史时代
('三国时代', 'placeholder://era/three_kingdoms.jpg', 'era', '三国争霸时代，英雄辈出', 'Ancient Three Kingdoms period scene, Chinese historical architecture, warriors, battle flags, heroic atmosphere, Chinese historical painting style, high quality, detailed ancient Chinese setting, military camp, traditional Chinese art, dramatic lighting, historical epic', '三国,历史,英雄,古代'),
('秦王朝', 'placeholder://era/qin_dynasty.jpg', 'era', '大秦帝国，统一六国', 'Qin Dynasty imperial scene, ancient Chinese palace, emperor, court officials, imperial atmosphere, Chinese historical painting style, high quality, detailed ancient Chinese architecture, imperial court, traditional Chinese art, majestic lighting, historical grandeur', '秦朝,历史,帝国,古代'),
('唐朝盛世', 'placeholder://era/tang_dynasty.jpg', 'era', '大唐盛世，文化繁荣', 'Tang Dynasty prosperous scene, magnificent Chinese architecture, cultural activities, prosperous city, golden age atmosphere, Chinese historical painting style, high quality, detailed ancient Chinese city, cultural prosperity, traditional Chinese art, golden lighting, historical splendor', '唐朝,历史,盛世,古代'),
('宋朝文雅', 'placeholder://era/song_dynasty.jpg', 'era', '宋朝文雅时代，诗词盛行', 'Song Dynasty elegant scene, refined Chinese architecture, scholars, poetry, elegant atmosphere, Chinese literati painting style, high quality, detailed ancient Chinese garden, cultural refinement, traditional Chinese art, soft lighting, historical elegance', '宋朝,历史,文雅,古代'),
('明朝江湖', 'placeholder://era/ming_dynasty.jpg', 'era', '明朝江湖时代，武侠世界', 'Ming Dynasty martial arts scene, ancient Chinese architecture, martial artists, swords, martial arts atmosphere, Chinese ink painting style, high quality, detailed ancient Chinese setting, martial arts world, traditional Chinese art, dramatic lighting, historical adventure', '明朝,历史,江湖,古代'),

-- 虚幻时代
('未来世界', 'placeholder://era/future_world.jpg', 'era', '未来世界，科技发达', 'Future world scene, futuristic city, advanced technology, flying vehicles, sci-fi atmosphere, sci-fi art style, high quality, detailed futuristic architecture, high-tech environment, science fiction art, neon lighting, futuristic vision', '未来,科技,科幻,虚幻'),
('赛博朋克都市', 'placeholder://era/cyberpunk_city.jpg', 'era', '赛博朋克都市，霓虹闪烁', 'Cyberpunk city scene, neon-lit streets, futuristic buildings, cyberpunk atmosphere, dark urban setting, cyberpunk art style, high quality, detailed cyberpunk architecture, neon colors, sci-fi art, dramatic neon lighting, dystopian future', '赛博朋克,都市,霓虹,虚幻'),
('魔法世界', 'placeholder://era/magic_world.jpg', 'era', '魔法世界，奇幻大陆', 'Magic world scene, fantasy landscape, magical creatures, floating islands, mystical atmosphere, fantasy art style, high quality, detailed fantasy environment, magical elements, fantasy art, ethereal lighting, enchanted realm', '魔法,世界,奇幻,虚幻'),
('童话世界', 'placeholder://era/fairy_tale_world.jpg', 'era', '童话世界，梦幻王国', 'Fairy tale world scene, enchanted forest, magical castles, talking animals, fairy tale characters, whimsical atmosphere, fantasy art style, high quality, detailed fairy tale environment, storybook setting, dreamy lighting, magical kingdom, colorful and vibrant, children''s story illustration style, fantasy landscape, enchanted realm', '童话,世界,梦幻,虚幻'),
('蒸汽朋克', 'placeholder://era/steampunk.jpg', 'era', '蒸汽朋克时代，机械美学', 'Steampunk era scene, Victorian architecture with gears, steam-powered machines, brass and copper, industrial atmosphere, steampunk art style, high quality, detailed steampunk machinery, mechanical aesthetics, steampunk art, warm industrial lighting, retro-futuristic', '蒸汽朋克,机械,复古,虚幻'),
('废土世界', 'placeholder://era/wasteland.jpg', 'era', '废土世界，末日之后', 'Post-apocalyptic wasteland scene, ruined buildings, desolate landscape, survival atmosphere, dystopian setting, post-apocalyptic art style, high quality, detailed wasteland environment, apocalyptic ruins, sci-fi art, harsh lighting, survival world', '废土,末日,生存,虚幻'),

-- 其他时代
('古代埃及', 'placeholder://era/ancient_egypt.jpg', 'era', '古埃及时代，法老王朝', 'Ancient Egypt scene, pyramids, pharaohs, hieroglyphs, ancient Egyptian atmosphere, historical art style, high quality, detailed ancient Egyptian architecture, desert setting, historical art, golden desert lighting, ancient civilization', '埃及,历史,法老,古代'),
('古希腊', 'placeholder://era/ancient_greece.jpg', 'era', '古希腊时代，神话传说', 'Ancient Greece scene, Greek temples, gods and heroes, marble columns, classical atmosphere, classical art style, high quality, detailed ancient Greek architecture, mythological setting, classical art, Mediterranean lighting, ancient civilization', '希腊,历史,神话,古代'),
('中世纪欧洲', 'placeholder://era/medieval_europe.jpg', 'era', '中世纪欧洲，骑士时代', 'Medieval Europe scene, castles, knights, medieval architecture, chivalric atmosphere, historical art style, high quality, detailed medieval architecture, feudal setting, historical art, dramatic castle lighting, medieval period', '中世纪,欧洲,骑士,历史'),
('文艺复兴', 'placeholder://era/renaissance.jpg', 'era', '文艺复兴时代，艺术繁荣', 'Renaissance era scene, Italian architecture, artists, art studios, cultural renaissance atmosphere, Renaissance art style, high quality, detailed Renaissance architecture, artistic setting, classical art, warm studio lighting, cultural golden age', '文艺复兴,艺术,文化,历史'),
('工业革命', 'placeholder://era/industrial_revolution.jpg', 'era', '工业革命时代，机器轰鸣', 'Industrial Revolution scene, factories, steam engines, industrial architecture, industrial atmosphere, historical art style, high quality, detailed industrial machinery, factory setting, industrial art, dramatic industrial lighting, technological revolution', '工业革命,机器,变革,历史');

-- ========== 角色类别 (Character) - 每个时代5-10个角色 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
-- 现实时代角色
('大学室友', 'placeholder://character/university_roommate.jpg', 'character', '大学室友，青春伙伴', 'A university roommate character, college student, friendly appearance, casual clothing, youthful atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, warm lighting, college life', '大学,室友,青春,现实'),
('大学导师', 'placeholder://character/university_professor.jpg', 'character', '大学导师，学术权威', 'A university professor character, scholarly appearance, professional attire, intellectual atmosphere, realistic style, high quality, detailed character design, academic setting, professional portrait, natural lighting, educational environment', '大学,导师,学术,现实'),
('大学同学', 'placeholder://character/university_classmate.jpg', 'character', '大学同学，同窗好友', 'A university classmate character, college student, friendly appearance, casual clothing, collaborative atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, natural lighting, college life', '大学,同学,友谊,现实'),
('大学学长', 'placeholder://character/university_senior.jpg', 'character', '大学学长，经验丰富', 'A university senior student character, older student, experienced appearance, casual clothing, mentoring atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, warm lighting, college guidance', '大学,学长,指导,现实'),
('大学社团伙伴', 'placeholder://character/university_club_member.jpg', 'character', '大学社团伙伴，志趣相投', 'A university club member character, college student, enthusiastic appearance, casual clothing, passionate atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, vibrant lighting, college activities', '大学,社团,兴趣,现实'),
('温柔学妹', 'placeholder://character/gentle_junior_sister.jpg', 'character', '温柔学妹，可爱纯真', 'A gentle junior sister character, female college student, soft appearance, cute clothing, gentle expression, innocent atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, soft lighting, college life', '大学,学妹,温柔,现实'),
('知性学姐', 'placeholder://character/intellectual_senior_sister.jpg', 'character', '知性学姐，优雅成熟', 'An intellectual senior sister character, female college student, elegant appearance, sophisticated clothing, wise expression, mature atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, warm lighting, college life', '大学,学姐,知性,现实'),
('帅气学长', 'placeholder://character/handsome_senior.jpg', 'character', '帅气学长，阳光自信', 'A handsome senior character, male college student, attractive appearance, stylish clothing, confident expression, sunny atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, bright lighting, college life', '大学,学长,帅气,现实'),
('文艺青年', 'placeholder://character/artistic_youth.jpg', 'character', '文艺青年，艺术气质', 'An artistic youth character, college student, creative appearance, bohemian clothing, thoughtful expression, artistic atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, soft lighting, college life', '大学,文艺,艺术,现实'),
('运动健将', 'placeholder://character/athletic_student.jpg', 'character', '运动健将，活力四射', 'An athletic student character, college student, fit appearance, sports clothing, energetic expression, active atmosphere, realistic style, high quality, detailed character design, modern setting, contemporary portrait, bright lighting, college life', '大学,运动,活力,现实'),
('中学同桌', 'placeholder://character/high_school_desk_mate.jpg', 'character', '中学同桌，青涩友谊', 'A high school desk mate character, teenager, school uniform, innocent expression, youthful atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, bright lighting, school life', '中学,同桌,友谊,现实'),
('中学老师', 'placeholder://character/high_school_teacher.jpg', 'character', '中学老师，传道授业', 'A high school teacher character, educator, professional appearance, formal clothing, nurturing atmosphere, realistic style, high quality, detailed character design, school setting, professional portrait, natural lighting, educational guidance', '中学,老师,教育,现实'),
('中学班长', 'placeholder://character/high_school_monitor.jpg', 'character', '中学班长，班级领袖', 'A high school monitor character, student leader, responsible appearance, school uniform, leadership atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, bright lighting, student leadership', '中学,班长,领导,现实'),
('中学好友', 'placeholder://character/high_school_friend.jpg', 'character', '中学好友，真挚友谊', 'A high school friend character, teenager, casual appearance, school uniform, friendly atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, warm lighting, teenage friendship', '中学,好友,友谊,现实'),
('中学运动伙伴', 'placeholder://character/high_school_sports_buddy.jpg', 'character', '中学运动伙伴，活力四射', 'A high school sports buddy character, athlete, energetic appearance, sports uniform, active atmosphere, realistic style, high quality, detailed character design, school setting, athletic portrait, bright lighting, sports activities', '中学,运动,活力,现实'),
('温柔同桌', 'placeholder://character/gentle_desk_mate.jpg', 'character', '温柔同桌，文静可爱', 'A gentle desk mate character, female high school student, soft appearance, school uniform, gentle expression, quiet atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, soft lighting, school life', '中学,同桌,温柔,现实'),
('阳光少年', 'placeholder://character/sunny_boy.jpg', 'character', '阳光少年，开朗活泼', 'A sunny boy character, male high school student, bright appearance, school uniform, cheerful expression, energetic atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, bright lighting, school life', '中学,少年,阳光,现实'),
('学霸班长', 'placeholder://character/study_monitor.jpg', 'character', '学霸班长，聪明优秀', 'A study monitor character, female high school student, intelligent appearance, school uniform, confident expression, academic atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, bright lighting, school life', '中学,班长,学霸,现实'),
('活泼学妹', 'placeholder://character/cheerful_junior.jpg', 'character', '活泼学妹，可爱活泼', 'A cheerful junior character, female high school student, cute appearance, school uniform, lively expression, energetic atmosphere, realistic style, high quality, detailed character design, school setting, teenage portrait, bright lighting, school life', '中学,学妹,活泼,现实'),
('运动健将', 'placeholder://character/athletic_student_hs.jpg', 'character', '运动健将，体育优秀', 'An athletic student character, male high school student, fit appearance, sports uniform, determined expression, athletic atmosphere, realistic style, high quality, detailed character design, school setting, athletic portrait, bright lighting, sports activities', '中学,运动,健将,现实'),
('职场同事', 'placeholder://character/workplace_colleague.jpg', 'character', '职场同事，工作伙伴', 'A workplace colleague character, professional appearance, business attire, friendly expression, professional atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, office lighting, work environment', '职场,同事,专业,现实'),
('职场上司', 'placeholder://character/workplace_boss.jpg', 'character', '职场上司，领导风范', 'A workplace boss character, executive appearance, formal business attire, authoritative expression, leadership atmosphere, realistic style, high quality, detailed character design, office setting, executive portrait, professional lighting, corporate leadership', '职场,上司,领导,现实'),
('职场新人', 'placeholder://character/workplace_newcomer.jpg', 'character', '职场新人，初入职场', 'A workplace newcomer character, young professional, eager appearance, business attire, enthusiastic expression, learning atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, bright lighting, career start', '职场,新人,成长,现实'),
('职场导师', 'placeholder://character/workplace_mentor.jpg', 'character', '职场导师，经验丰富', 'A workplace mentor character, experienced professional, wise appearance, business attire, guiding expression, mentoring atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, warm lighting, career guidance', '职场,导师,指导,现实'),
('职场合作伙伴', 'placeholder://character/workplace_partner.jpg', 'character', '职场合作伙伴，协作共赢', 'A workplace partner character, professional appearance, business attire, collaborative expression, partnership atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, professional lighting, business collaboration', '职场,合作,协作,现实'),
('知性女上司', 'placeholder://character/intellectual_female_boss.jpg', 'character', '知性女上司，优雅干练', 'An intellectual female boss character, professional woman, elegant appearance, business attire, confident expression, leadership atmosphere, realistic style, high quality, detailed character design, office setting, executive portrait, professional lighting, corporate leadership', '职场,上司,知性,现实'),
('温柔女同事', 'placeholder://character/gentle_female_colleague.jpg', 'character', '温柔女同事，友善亲切', 'A gentle female colleague character, professional woman, soft appearance, business attire, friendly expression, warm atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, warm lighting, work environment', '职场,同事,温柔,现实'),
('帅气男上司', 'placeholder://character/handsome_male_boss.jpg', 'character', '帅气男上司，成熟稳重', 'A handsome male boss character, professional man, attractive appearance, business attire, confident expression, leadership atmosphere, realistic style, high quality, detailed character design, office setting, executive portrait, professional lighting, corporate leadership', '职场,上司,帅气,现实'),
('职场新人女', 'placeholder://character/workplace_newcomer_female.jpg', 'character', '职场新人，温柔好学', 'A workplace newcomer character, young professional woman, gentle appearance, business attire, eager expression, learning atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, bright lighting, career start', '职场,新人,温柔,现实'),
('职场新人男', 'placeholder://character/workplace_newcomer_male.jpg', 'character', '职场新人，阳光上进', 'A workplace newcomer character, young professional man, bright appearance, business attire, enthusiastic expression, learning atmosphere, realistic style, high quality, detailed character design, office setting, professional portrait, bright lighting, career start', '职场,新人,阳光,现实'),
('童年玩伴', 'placeholder://character/childhood_friend.jpg', 'character', '童年玩伴，纯真友谊', 'A childhood friend character, child, playful appearance, casual clothing, innocent atmosphere, realistic style, high quality, detailed character design, childhood setting, nostalgic portrait, warm lighting, childhood memories', '童年,玩伴,纯真,现实'),
('童年邻居', 'placeholder://character/childhood_neighbor.jpg', 'character', '童年邻居，亲切温暖', 'A childhood neighbor character, friendly adult or child, warm appearance, casual clothing, neighborly atmosphere, realistic style, high quality, detailed character design, neighborhood setting, nostalgic portrait, warm lighting, childhood community', '童年,邻居,温暖,现实'),
('童年老师', 'placeholder://character/childhood_teacher.jpg', 'character', '童年老师，启蒙教育', 'A childhood teacher character, elementary teacher, kind appearance, casual clothing, nurturing expression, educational atmosphere, realistic style, high quality, detailed character design, school setting, nostalgic portrait, warm lighting, childhood education', '童年,老师,教育,现实'),
('童年长辈', 'placeholder://character/childhood_elder.jpg', 'character', '童年长辈，慈爱关怀', 'A childhood elder character, grandparent or older relative, wise appearance, traditional clothing, loving expression, caring atmosphere, realistic style, high quality, detailed character design, home setting, nostalgic portrait, warm lighting, family care', '童年,长辈,慈爱,现实'),
('童年宠物', 'placeholder://character/childhood_pet.jpg', 'character', '童年宠物，忠实伙伴', 'A childhood pet character, dog or cat, cute appearance, playful expression, loyal atmosphere, realistic style, high quality, detailed character design, home setting, nostalgic portrait, warm lighting, childhood companion', '童年,宠物,伙伴,现实'),
('温柔小女孩', 'placeholder://character/gentle_little_girl.jpg', 'character', '温柔小女孩，纯真可爱', 'A gentle little girl character, young girl, soft appearance, cute clothing, innocent expression, pure atmosphere, realistic style, high quality, detailed character design, childhood setting, nostalgic portrait, warm lighting, childhood memories', '童年,女孩,温柔,现实'),
('活泼小男孩', 'placeholder://character/cheerful_little_boy.jpg', 'character', '活泼小男孩，调皮可爱', 'A cheerful little boy character, young boy, bright appearance, casual clothing, playful expression, energetic atmosphere, realistic style, high quality, detailed character design, childhood setting, nostalgic portrait, warm lighting, childhood memories', '童年,男孩,活泼,现实'),
('温柔女老师', 'placeholder://character/gentle_female_teacher.jpg', 'character', '温柔女老师，慈爱耐心', 'A gentle female teacher character, elementary teacher, soft appearance, casual clothing, kind expression, nurturing atmosphere, realistic style, high quality, detailed character design, school setting, nostalgic portrait, warm lighting, childhood education', '童年,老师,温柔,现实'),
('慈祥奶奶', 'placeholder://character/kind_grandmother.jpg', 'character', '慈祥奶奶，温暖慈爱', 'A kind grandmother character, elderly woman, warm appearance, traditional clothing, loving expression, caring atmosphere, realistic style, high quality, detailed character design, home setting, nostalgic portrait, warm lighting, family care', '童年,奶奶,慈祥,现实'),
('和蔼爷爷', 'placeholder://character/kind_grandfather.jpg', 'character', '和蔼爷爷，慈祥可亲', 'A kind grandfather character, elderly man, warm appearance, traditional clothing, friendly expression, caring atmosphere, realistic style, high quality, detailed character design, home setting, nostalgic portrait, warm lighting, family care', '童年,爷爷,和蔼,现实'),
('故乡长辈', 'placeholder://character/hometown_elder.jpg', 'character', '故乡长辈，乡音亲切', 'A hometown elder character, village elder, traditional appearance, local clothing, warm expression, nostalgic atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown memories', '故乡,长辈,亲切,现实'),
('故乡伙伴', 'placeholder://character/hometown_friend.jpg', 'character', '故乡伙伴，青梅竹马', 'A hometown friend character, childhood friend, familiar appearance, casual clothing, friendly expression, nostalgic atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown friendship', '故乡,伙伴,友谊,现实'),
('故乡商贩', 'placeholder://character/hometown_vendor.jpg', 'character', '故乡商贩，熟悉面孔', 'A hometown vendor character, local merchant, friendly appearance, traditional clothing, welcoming expression, nostalgic atmosphere, realistic style, high quality, detailed character design, hometown market setting, nostalgic portrait, warm lighting, hometown commerce', '故乡,商贩,熟悉,现实'),
('故乡老师', 'placeholder://character/hometown_teacher.jpg', 'character', '故乡老师，启蒙之恩', 'A hometown teacher character, local educator, kind appearance, simple clothing, nurturing expression, educational atmosphere, realistic style, high quality, detailed character design, hometown school setting, nostalgic portrait, warm lighting, hometown education', '故乡,老师,教育,现实'),
('故乡邻居', 'placeholder://character/hometown_neighbor.jpg', 'character', '故乡邻居，邻里情深', 'A hometown neighbor character, friendly local, warm appearance, casual clothing, neighborly expression, community atmosphere, realistic style, high quality, detailed character design, hometown neighborhood setting, nostalgic portrait, warm lighting, hometown community', '故乡,邻居,邻里,现实'),
('温柔故乡女孩', 'placeholder://character/gentle_hometown_girl.jpg', 'character', '温柔故乡女孩，纯真善良', 'A gentle hometown girl character, young woman, soft appearance, traditional clothing, innocent expression, pure atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown memories', '故乡,女孩,温柔,现实'),
('阳光故乡少年', 'placeholder://character/sunny_hometown_boy.jpg', 'character', '阳光故乡少年，开朗热情', 'A sunny hometown boy character, young man, bright appearance, casual clothing, cheerful expression, energetic atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown memories', '故乡,少年,阳光,现实'),
('慈祥故乡奶奶', 'placeholder://character/kind_hometown_grandmother.jpg', 'character', '慈祥故乡奶奶，温暖亲切', 'A kind hometown grandmother character, elderly woman, warm appearance, traditional clothing, loving expression, caring atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown memories', '故乡,奶奶,慈祥,现实'),
('和蔼故乡爷爷', 'placeholder://character/kind_hometown_grandfather.jpg', 'character', '和蔼故乡爷爷，慈祥可亲', 'A kind hometown grandfather character, elderly man, warm appearance, traditional clothing, friendly expression, caring atmosphere, realistic style, high quality, detailed character design, hometown setting, nostalgic portrait, warm lighting, hometown memories', '故乡,爷爷,和蔼,现实'),

-- 历史时代角色 - 三国
('刘备', 'placeholder://character/liu_bei.jpg', 'character', '蜀汉昭烈帝，仁德之主', 'Liu Bei character, Three Kingdoms period, emperor appearance, traditional Chinese clothing, noble expression, heroic atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, traditional portrait, dramatic lighting, historical figure', '三国,刘备,皇帝,历史'),
('关羽', 'placeholder://character/guan_yu.jpg', 'character', '武圣关羽，忠义无双', 'Guan Yu character, Three Kingdoms period, warrior appearance, traditional Chinese armor, heroic expression, martial atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, warrior portrait, dramatic lighting, legendary hero', '三国,关羽,武将,历史'),
('诸葛亮', 'placeholder://character/zhuge_liang.jpg', 'character', '卧龙诸葛亮，智谋超群', 'Zhuge Liang character, Three Kingdoms period, scholar appearance, traditional Chinese robes, wise expression, intellectual atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, scholar portrait, soft lighting, legendary strategist', '三国,诸葛亮,谋士,历史'),
('曹操', 'placeholder://character/cao_cao.jpg', 'character', '魏武帝曹操，一代枭雄', 'Cao Cao character, Three Kingdoms period, emperor appearance, traditional Chinese imperial clothing, ambitious expression, powerful atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, imperial portrait, dramatic lighting, historical ruler', '三国,曹操,皇帝,历史'),
('周瑜', 'placeholder://character/zhou_yu.jpg', 'character', '东吴周瑜，文武双全', 'Zhou Yu character, Three Kingdoms period, general appearance, traditional Chinese military clothing, talented expression, heroic atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, general portrait, dramatic lighting, talented general', '三国,周瑜,将军,历史'),

-- 历史时代角色 - 唐朝
('李白', 'placeholder://character/li_bai.jpg', 'character', '诗仙李白，浪漫诗人', 'Li Bai character, Tang Dynasty, poet appearance, traditional Chinese scholar clothing, romantic expression, poetic atmosphere, Chinese literati painting style, high quality, detailed character design, ancient Chinese setting, poet portrait, soft lighting, legendary poet', '唐朝,李白,诗人,历史'),
('杜甫', 'placeholder://character/du_fu.jpg', 'character', '诗圣杜甫，现实主义诗人', 'Du Fu character, Tang Dynasty, poet appearance, traditional Chinese scholar clothing, thoughtful expression, realistic atmosphere, Chinese literati painting style, high quality, detailed character design, ancient Chinese setting, poet portrait, natural lighting, great poet', '唐朝,杜甫,诗人,历史'),
('武则天', 'placeholder://character/wu_zetian.jpg', 'character', '女皇武则天，唯一女帝', 'Wu Zetian character, Tang Dynasty, empress appearance, traditional Chinese imperial clothing, powerful expression, imperial atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, empress portrait, majestic lighting, only female emperor', '唐朝,武则天,皇帝,历史'),
('杨贵妃', 'placeholder://character/yang_guifei.jpg', 'character', '杨贵妃，四大美女之一', 'Yang Guifei character, Tang Dynasty, beautiful woman appearance, elegant traditional Chinese clothing, graceful expression, beautiful atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, beauty portrait, soft lighting, legendary beauty', '唐朝,杨贵妃,美女,历史'),
('唐太宗', 'placeholder://character/tang_taizong.jpg', 'character', '唐太宗李世民，贞观之治', 'Tang Taizong Li Shimin character, Tang Dynasty, emperor appearance, traditional Chinese imperial clothing, wise expression, imperial atmosphere, Chinese historical painting style, high quality, detailed character design, ancient Chinese setting, emperor portrait, majestic lighting, great emperor', '唐朝,唐太宗,皇帝,历史'),

-- 虚幻时代角色 - 未来世界
('未来战士', 'placeholder://character/future_warrior.jpg', 'character', '未来战士，科技武装', 'Future warrior character, sci-fi style, advanced combat armor, high-tech weapons, determined expression, futuristic atmosphere, sci-fi art style, high quality, detailed character design, futuristic setting, sci-fi portrait, neon lighting, future soldier', '未来,战士,科技,虚幻'),
('AI助手', 'placeholder://character/ai_assistant.jpg', 'character', 'AI助手，智能伙伴', 'AI assistant character, sci-fi style, holographic appearance, digital effects, friendly expression, technological atmosphere, sci-fi art style, high quality, detailed character design, futuristic setting, digital portrait, blue lighting, artificial intelligence', '未来,AI,智能,虚幻'),
('太空探索者', 'placeholder://character/space_explorer.jpg', 'character', '太空探索者，星际旅行', 'Space explorer character, sci-fi style, space suit, advanced equipment, adventurous expression, space atmosphere, sci-fi art style, high quality, detailed character design, space setting, astronaut portrait, cosmic lighting, space adventurer', '未来,太空,探索,虚幻'),
('未来科学家', 'placeholder://character/future_scientist.jpg', 'character', '未来科学家，科技先锋', 'Future scientist character, sci-fi style, lab coat, advanced technology, intelligent expression, scientific atmosphere, sci-fi art style, high quality, detailed character design, futuristic lab setting, scientist portrait, bright lighting, scientific innovation', '未来,科学家,科技,虚幻'),
('未来工程师', 'placeholder://character/future_engineer.jpg', 'character', '未来工程师，技术专家', 'Future engineer character, sci-fi style, technical gear, advanced tools, focused expression, technological atmosphere, sci-fi art style, high quality, detailed character design, futuristic workshop setting, engineer portrait, industrial lighting, technical expertise', '未来,工程师,技术,虚幻'),

-- 虚幻时代角色 - 魔法世界
('魔法师', 'placeholder://character/mage.jpg', 'character', '魔法师，掌控元素', 'Mage character, fantasy style, wizard robes, magical staff, mystical expression, magical atmosphere, fantasy art style, high quality, detailed character design, fantasy setting, wizard portrait, magical lighting, powerful mage', '魔法,法师,元素,虚幻'),
('精灵弓箭手', 'placeholder://character/elf_archer.jpg', 'character', '精灵弓箭手，精准射击', 'Elf archer character, fantasy style, pointed ears, elegant clothing, bow and arrow, graceful expression, fantasy atmosphere, fantasy art style, high quality, detailed character design, fantasy setting, elf portrait, ethereal lighting, skilled archer', '魔法,精灵,弓箭,虚幻'),
('龙骑士', 'placeholder://character/dragon_knight.jpg', 'character', '龙骑士，驾驭巨龙', 'Dragon knight character, fantasy style, knight armor, dragon companion, heroic expression, epic atmosphere, fantasy art style, high quality, detailed character design, fantasy setting, knight portrait, dramatic lighting, legendary rider', '魔法,龙骑士,英雄,虚幻'),
('魔法学徒', 'placeholder://character/magic_apprentice.jpg', 'character', '魔法学徒，学习成长', 'Magic apprentice character, fantasy style, simple robes, beginner staff, eager expression, learning atmosphere, fantasy art style, high quality, detailed character design, fantasy setting, apprentice portrait, soft lighting, young mage', '魔法,学徒,成长,虚幻'),
('精灵法师', 'placeholder://character/elf_mage.jpg', 'character', '精灵法师，自然魔法', 'Elf mage character, fantasy style, pointed ears, elegant robes, nature staff, graceful expression, fantasy atmosphere, fantasy art style, high quality, detailed character design, fantasy setting, elf mage portrait, ethereal lighting, nature magic', '魔法,精灵,自然,虚幻'),

-- 虚幻时代角色 - 赛博朋克
('赛博黑客', 'placeholder://character/cyber_hacker.jpg', 'character', '赛博黑客，数字游侠', 'Cyber hacker character, cyberpunk style, cybernetic enhancements, digital interface, tech-savvy expression, cyberpunk atmosphere, cyberpunk art style, high quality, detailed character design, cyberpunk setting, hacker portrait, neon lighting, digital outlaw', '赛博朋克,黑客,数字,虚幻'),
('义体改造人', 'placeholder://character/cyborg.jpg', 'character', '义体改造人，人机融合', 'Cyborg character, cyberpunk style, mechanical parts, human-robot fusion, determined expression, cyberpunk atmosphere, cyberpunk art style, high quality, detailed character design, cyberpunk setting, cyborg portrait, neon lighting, enhanced human', '赛博朋克,义体,改造,虚幻'),
('赛博警察', 'placeholder://character/cyber_cop.jpg', 'character', '赛博警察，维护秩序', 'Cyber cop character, cyberpunk style, law enforcement gear, cybernetic enhancements, authoritative expression, cyberpunk atmosphere, cyberpunk art style, high quality, detailed character design, cyberpunk setting, police portrait, neon lighting, law enforcement', '赛博朋克,警察,秩序,虚幻'),
('赛博商人', 'placeholder://character/cyber_merchant.jpg', 'character', '赛博商人，商业精英', 'Cyber merchant character, cyberpunk style, business attire, digital interface, shrewd expression, cyberpunk atmosphere, cyberpunk art style, high quality, detailed character design, cyberpunk setting, merchant portrait, neon lighting, business elite', '赛博朋克,商人,商业,虚幻'),
('赛博医生', 'placeholder://character/cyber_doctor.jpg', 'character', '赛博医生，义体修复', 'Cyber doctor character, cyberpunk style, medical gear, cybernetic tools, professional expression, cyberpunk atmosphere, cyberpunk art style, high quality, detailed character design, cyberpunk clinic setting, doctor portrait, neon lighting, cybernetic medicine', '赛博朋克,医生,医疗,虚幻'),

-- 虚幻时代角色 - 童话世界
('童话公主', 'placeholder://character/fairy_tale_princess.jpg', 'character', '童话公主，美丽善良', 'Fairy tale princess character, beautiful princess appearance, elegant ball gown, tiara, graceful expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, princess portrait, dreamy lighting, kind-hearted princess, storybook style, magical charm', '童话,公主,美丽,虚幻'),
('童话王子', 'placeholder://character/fairy_tale_prince.jpg', 'character', '童话王子，英俊勇敢', 'Fairy tale prince character, handsome prince appearance, royal attire, crown, brave expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, prince portrait, heroic lighting, brave prince, storybook style, noble character', '童话,王子,勇敢,虚幻'),
('小精灵', 'placeholder://character/fairy.jpg', 'character', '小精灵，活泼可爱', 'Fairy character, tiny magical creature, delicate wings, sparkling appearance, playful expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, fairy portrait, magical lighting, cute fairy, storybook style, whimsical charm', '童话,精灵,可爱,虚幻'),
('仙女', 'placeholder://character/fairy_godmother.jpg', 'character', '仙女，温柔慈爱', 'Fairy godmother character, elegant magical being, flowing robes, wand, kind expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, fairy godmother portrait, ethereal lighting, benevolent fairy, storybook style, magical wisdom', '童话,仙女,慈爱,虚幻'),
('童话魔法师', 'placeholder://character/fairy_tale_wizard.jpg', 'character', '童话魔法师，神秘强大', 'Fairy tale wizard character, wise old wizard appearance, pointed hat, magical staff, mystical expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, wizard portrait, magical lighting, powerful wizard, storybook style, ancient magic', '童话,魔法师,神秘,虚幻'),
('童话骑士', 'placeholder://character/fairy_tale_knight.jpg', 'character', '童话骑士，守护正义', 'Fairy tale knight character, brave knight appearance, shining armor, sword, heroic expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, knight portrait, heroic lighting, noble knight, storybook style, chivalrous hero', '童话,骑士,正义,虚幻'),
('小矮人', 'placeholder://character/dwarf.jpg', 'character', '小矮人，勤劳善良', 'Dwarf character, small stature, bearded appearance, mining tools, friendly expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, dwarf portrait, warm lighting, hardworking dwarf, storybook style, cheerful character', '童话,矮人,勤劳,虚幻'),
('童话女巫', 'placeholder://character/fairy_tale_witch.jpg', 'character', '童话女巫，神秘莫测', 'Fairy tale witch character, mysterious witch appearance, dark robes, magical potions, enigmatic expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, witch portrait, mystical lighting, mysterious witch, storybook style, magical powers', '童话,女巫,神秘,虚幻'),
('小红帽', 'placeholder://character/little_red_riding_hood.jpg', 'character', '小红帽，纯真勇敢', 'Little Red Riding Hood character, young girl appearance, red hood, basket, innocent yet brave expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, little girl portrait, forest lighting, brave girl, storybook style, classic character', '童话,小红帽,纯真,虚幻'),
('灰姑娘', 'placeholder://character/cinderella.jpg', 'character', '灰姑娘，善良美丽', 'Cinderella character, beautiful young woman appearance, simple dress transforming to ball gown, glass slippers, kind expression, fairy tale atmosphere, children''s story illustration style, high quality, detailed character design, fairy tale setting, cinderella portrait, magical lighting, kind-hearted girl, storybook style, classic princess', '童话,灰姑娘,善良,虚幻');

-- ========== 剧本类别 (Scenario) - 至少5个 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
('校园青春剧', 'placeholder://scenario/campus_youth.jpg', 'scenario', '校园青春剧本，青春成长故事', 'A campus youth drama scene, school setting, students, youthful atmosphere, emotional moments, realistic style, high quality, detailed school environment, teenage life, dramatic composition, natural lighting, coming-of-age story, emotional depth', '校园,青春,成长,剧本'),
('职场奋斗剧', 'placeholder://scenario/workplace_struggle.jpg', 'scenario', '职场奋斗剧本，事业与人生', 'A workplace struggle drama scene, office setting, professionals, business atmosphere, career challenges, realistic style, high quality, detailed office environment, professional life, dramatic composition, office lighting, career story, personal growth', '职场,奋斗,事业,剧本'),
('历史史诗剧', 'placeholder://scenario/historical_epic.jpg', 'scenario', '历史史诗剧本，英雄传奇', 'A historical epic drama scene, ancient setting, historical figures, heroic atmosphere, grand scale, Chinese historical painting style, high quality, detailed historical environment, ancient times, epic composition, dramatic lighting, legendary story, historical grandeur', '历史,史诗,英雄,剧本'),
('科幻冒险剧', 'placeholder://scenario/sci_fi_adventure.jpg', 'scenario', '科幻冒险剧本，未来探索', 'A sci-fi adventure drama scene, futuristic setting, space explorers, technological atmosphere, adventure elements, sci-fi art style, high quality, detailed futuristic environment, space age, dynamic composition, neon lighting, space adventure, technological wonder', '科幻,冒险,未来,剧本'),
('奇幻魔法剧', 'placeholder://scenario/fantasy_magic.jpg', 'scenario', '奇幻魔法剧本，魔法世界', 'A fantasy magic drama scene, magical setting, wizards and creatures, mystical atmosphere, magical elements, fantasy art style, high quality, detailed fantasy environment, magical realm, epic composition, magical lighting, fantasy adventure, enchanted world', '奇幻,魔法,冒险,剧本'),
('悬疑推理剧', 'placeholder://scenario/mystery_thriller.jpg', 'scenario', '悬疑推理剧本，谜题重重', 'A mystery thriller drama scene, mysterious setting, detectives, suspenseful atmosphere, mystery elements, noir style, high quality, detailed mysterious environment, crime scene, dramatic composition, dramatic shadows, mystery story, suspenseful plot', '悬疑,推理,谜题,剧本'),
('爱情浪漫剧', 'placeholder://scenario/romance.jpg', 'scenario', '爱情浪漫剧本，情感纠葛', 'A romance drama scene, romantic setting, couples, emotional atmosphere, love story elements, realistic style, high quality, detailed romantic environment, relationship dynamics, emotional composition, soft lighting, love story, romantic moments', '爱情,浪漫,情感,剧本'),
('武侠江湖剧', 'placeholder://scenario/martial_arts.jpg', 'scenario', '武侠江湖剧本，快意恩仇', 'A martial arts drama scene, ancient Chinese setting, warriors, martial arts atmosphere, action elements, Chinese ink painting style, high quality, detailed ancient Chinese environment, martial arts world, dynamic composition, dramatic lighting, wuxia story, heroic adventure', '武侠,江湖,英雄,剧本');

-- ========== 日记类别 (Journal) - 至少20个 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
-- 日常日记
('晨间日记', 'placeholder://journal/morning_journal.jpg', 'journal', '晨间日记，新的一天开始', 'A morning journal scene, sunrise, peaceful morning atmosphere, journal book, pen, soft morning light, realistic style, high quality, detailed journal setting, morning routine, warm lighting, new day beginning, peaceful moment', '晨间,日记,日常,现实'),
('夜晚反思', 'placeholder://journal/night_reflection.jpg', 'journal', '夜晚反思日记，一天的总结', 'A night reflection journal scene, moonlit night, quiet atmosphere, journal book, candlelight, peaceful evening, realistic style, high quality, detailed journal setting, evening routine, soft candlelight, daily reflection, quiet moment', '夜晚,反思,日常,现实'),
('工作记录', 'placeholder://journal/work_record.jpg', 'journal', '工作记录日记，职场点滴', 'A work record journal scene, office setting, professional atmosphere, journal book, work notes, business environment, realistic style, high quality, detailed journal setting, workplace, office lighting, work documentation, professional record', '工作,记录,职场,现实'),
('学习笔记', 'placeholder://journal/study_notes.jpg', 'journal', '学习笔记日记，知识积累', 'A study notes journal scene, study room, academic atmosphere, journal book, study materials, educational setting, realistic style, high quality, detailed journal setting, learning environment, natural lighting, study documentation, knowledge accumulation', '学习,笔记,教育,现实'),
('旅行日记', 'placeholder://journal/travel_diary.jpg', 'journal', '旅行日记，旅途见闻', 'A travel diary scene, travel setting, adventurous atmosphere, journal book, travel souvenirs, exotic location, realistic style, high quality, detailed journal setting, travel environment, natural lighting, travel documentation, adventure record', '旅行,日记,冒险,现实'),

-- 情感日记
('心情日记', 'placeholder://journal/mood_journal.jpg', 'journal', '心情日记，情感记录', 'A mood journal scene, emotional setting, personal atmosphere, journal book, emotional expression, intimate space, realistic style, high quality, detailed journal setting, personal space, soft lighting, emotional documentation, personal reflection', '心情,情感,个人,现实'),
('感恩日记', 'placeholder://journal/gratitude_journal.jpg', 'journal', '感恩日记，记录美好', 'A gratitude journal scene, warm setting, positive atmosphere, journal book, thankful elements, cozy environment, realistic style, high quality, detailed journal setting, positive space, warm lighting, gratitude documentation, positive reflection', '感恩,美好,积极,现实'),
('梦想日记', 'placeholder://journal/dream_journal.jpg', 'journal', '梦想日记，未来规划', 'A dream journal scene, inspirational setting, hopeful atmosphere, journal book, dream elements, inspiring environment, realistic style, high quality, detailed journal setting, dream space, bright lighting, dream documentation, future planning', '梦想,规划,未来,现实'),

-- 主题日记
('读书笔记', 'placeholder://journal/reading_notes.jpg', 'journal', '读书笔记日记，阅读感悟', 'A reading notes journal scene, library setting, literary atmosphere, journal book, books, reading environment, realistic style, high quality, detailed journal setting, reading space, natural lighting, reading documentation, literary reflection', '读书,阅读,文学,现实'),
('美食日记', 'placeholder://journal/food_diary.jpg', 'journal', '美食日记，味觉记忆', 'A food diary scene, kitchen setting, culinary atmosphere, journal book, food elements, cooking environment, realistic style, high quality, detailed journal setting, culinary space, warm lighting, food documentation, culinary memory', '美食,烹饪,味觉,现实'),
('运动日记', 'placeholder://journal/fitness_journal.jpg', 'journal', '运动日记，健康记录', 'A fitness journal scene, gym setting, active atmosphere, journal book, fitness equipment, sports environment, realistic style, high quality, detailed journal setting, fitness space, bright lighting, fitness documentation, health record', '运动,健康,健身,现实'),
('艺术日记', 'placeholder://journal/art_journal.jpg', 'journal', '艺术日记，创作记录', 'An art journal scene, studio setting, creative atmosphere, journal book, art supplies, artistic environment, realistic style, high quality, detailed journal setting, creative space, studio lighting, art documentation, creative expression', '艺术,创作,创意,现实'),

-- 特殊日记
('梦境记录', 'placeholder://journal/dream_record.jpg', 'journal', '梦境记录日记，潜意识探索', 'A dream record journal scene, mystical setting, dreamy atmosphere, journal book, dream elements, surreal environment, fantasy art style, high quality, detailed journal setting, dream space, ethereal lighting, dream documentation, subconscious exploration', '梦境,潜意识,神秘,通用'),
('灵感捕捉', 'placeholder://journal/inspiration_capture.jpg', 'journal', '灵感捕捉日记，创意收集', 'An inspiration capture journal scene, creative setting, inspiring atmosphere, journal book, creative elements, inspiring environment, artistic style, high quality, detailed journal setting, creative space, bright lighting, inspiration documentation, idea collection', '灵感,创意,收集,通用'),
('成长记录', 'placeholder://journal/growth_record.jpg', 'journal', '成长记录日记，人生轨迹', 'A growth record journal scene, personal setting, reflective atmosphere, journal book, growth elements, personal space, realistic style, high quality, detailed journal setting, personal environment, natural lighting, growth documentation, life journey', '成长,记录,人生,现实'),
('回忆录', 'placeholder://journal/memoir.jpg', 'journal', '回忆录日记，往事如烟', 'A memoir journal scene, nostalgic setting, memory atmosphere, journal book, old photos, nostalgic environment, realistic style, high quality, detailed journal setting, memory space, warm lighting, memory documentation, past memories', '回忆,往事,怀旧,现实'),

-- 其他日记
('观察日记', 'placeholder://journal/observation_journal.jpg', 'journal', '观察日记，细节记录', 'An observation journal scene, detailed setting, observant atmosphere, journal book, observation tools, detailed environment, realistic style, high quality, detailed journal setting, observation space, natural lighting, observation documentation, detail recording', '观察,细节,记录,通用'),
('思考日记', 'placeholder://journal/thinking_journal.jpg', 'journal', '思考日记，深度思考', 'A thinking journal scene, contemplative setting, thoughtful atmosphere, journal book, thinking elements, quiet environment, realistic style, high quality, detailed journal setting, thinking space, soft lighting, thinking documentation, deep reflection', '思考,深度,哲学,通用'),
('计划日记', 'placeholder://journal/planning_journal.jpg', 'journal', '计划日记，目标规划', 'A planning journal scene, organized setting, planning atmosphere, journal book, planning tools, organized environment, realistic style, high quality, detailed journal setting, planning space, bright lighting, planning documentation, goal setting', '计划,目标,规划,现实'),
('总结日记', 'placeholder://journal/summary_journal.jpg', 'journal', '总结日记，回顾总结', 'A summary journal scene, reflective setting, summary atmosphere, journal book, summary elements, reflective environment, realistic style, high quality, detailed journal setting, reflection space, natural lighting, summary documentation, review and reflection', '总结,回顾,反思,现实');

-- ========== 通用类别 (General) - 至少20个 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`) VALUES
-- 自然场景
('山川河流', 'placeholder://general/mountains_rivers.jpg', 'general', '山川河流，自然风光', 'Mountains and rivers landscape, natural scenery, flowing water, mountain peaks, natural beauty, realistic style, high quality, detailed natural environment, scenic landscape, natural lighting, peaceful nature, majestic scenery', '山川,河流,自然,通用'),
('森林秘境', 'placeholder://general/forest_secret.jpg', 'general', '森林秘境，神秘自然', 'Secret forest scene, dense trees, mysterious atmosphere, natural setting, forest environment, realistic style, high quality, detailed forest landscape, mystical nature, dappled lighting, enchanted forest, natural mystery', '森林,秘境,自然,通用'),
('海边日落', 'placeholder://general/beach_sunset.jpg', 'general', '海边日落，浪漫时刻', 'Beach sunset scene, ocean, golden hour, romantic atmosphere, coastal setting, realistic style, high quality, detailed beach landscape, sunset beauty, warm golden lighting, romantic moment, coastal scenery', '海边,日落,浪漫,通用'),
('星空夜晚', 'placeholder://general/starry_night.jpg', 'general', '星空夜晚，宇宙浩瀚', 'Starry night scene, starry sky, night atmosphere, cosmic setting, astronomical beauty, realistic style, high quality, detailed night sky, starry landscape, dark night lighting, cosmic wonder, astronomical scene', '星空,夜晚,宇宙,通用'),

-- 建筑场景
('现代都市', 'placeholder://general/modern_city.jpg', 'general', '现代都市，繁华都市', 'Modern city scene, skyscrapers, urban atmosphere, contemporary architecture, city setting, realistic style, high quality, detailed urban landscape, modern architecture, city lighting, urban life, metropolitan scene', '都市,现代,建筑,通用'),
('古建筑群', 'placeholder://general/ancient_architecture.jpg', 'general', '古建筑群，历史沉淀', 'Ancient architecture complex, traditional buildings, historical atmosphere, classical architecture, historical setting, Chinese historical painting style, high quality, detailed ancient architecture, traditional buildings, historical lighting, cultural heritage, architectural beauty', '古建筑,历史,文化,通用'),
('欧式城堡', 'placeholder://general/european_castle.jpg', 'general', '欧式城堡，童话世界', 'European castle scene, medieval architecture, fairy tale atmosphere, castle setting, romantic architecture, realistic style, high quality, detailed castle landscape, medieval architecture, dramatic lighting, fairy tale world, architectural grandeur', '城堡,欧洲,童话,通用'),

-- 抽象概念
('时间流逝', 'placeholder://general/time_passing.jpg', 'general', '时间流逝，岁月如梭', 'Time passing concept, clock elements, temporal atmosphere, abstract setting, time concept, abstract art style, high quality, detailed abstract composition, time symbolism, dramatic lighting, temporal flow, conceptual art', '时间,抽象,概念,通用'),
('梦想飞翔', 'placeholder://general/dream_flying.jpg', 'general', '梦想飞翔，自由向往', 'Dream flying concept, wings, freedom atmosphere, inspirational setting, dream concept, fantasy art style, high quality, detailed abstract composition, freedom symbolism, ethereal lighting, dream flight, inspirational art', '梦想,飞翔,自由,通用'),
('希望之光', 'placeholder://general/light_of_hope.jpg', 'general', '希望之光，光明未来', 'Light of hope concept, light rays, hopeful atmosphere, inspirational setting, hope concept, abstract art style, high quality, detailed abstract composition, hope symbolism, bright lighting, hopeful future, inspirational art', '希望,光明,未来,通用'),

-- 物品场景
('书籍堆叠', 'placeholder://general/book_stack.jpg', 'general', '书籍堆叠，知识海洋', 'Book stack scene, books, literary atmosphere, library setting, knowledge concept, realistic style, high quality, detailed book composition, literary environment, warm lighting, knowledge collection, reading scene', '书籍,知识,文学,通用'),
('咖啡时光', 'placeholder://general/coffee_time.jpg', 'general', '咖啡时光，悠闲午后', 'Coffee time scene, coffee cup, cozy atmosphere, cafe setting, relaxation concept, realistic style, high quality, detailed cafe composition, cozy environment, warm lighting, relaxing moment, cafe scene', '咖啡,悠闲,生活,通用'),
('音乐旋律', 'placeholder://general/music_melody.jpg', 'general', '音乐旋律，艺术之美', 'Music melody concept, musical instruments, artistic atmosphere, music setting, art concept, abstract art style, high quality, detailed musical composition, artistic environment, dramatic lighting, musical beauty, artistic scene', '音乐,艺术,旋律,通用'),

-- 其他通用
('四季变换', 'placeholder://general/four_seasons.jpg', 'general', '四季变换，时光流转', 'Four seasons transformation, seasonal elements, temporal atmosphere, nature setting, time concept, realistic style, high quality, detailed seasonal composition, natural environment, seasonal lighting, time flow, seasonal beauty', '四季,时间,自然,通用'),
('城市夜景', 'placeholder://general/city_night.jpg', 'general', '城市夜景，霓虹闪烁', 'City night scene, urban lights, night atmosphere, city setting, urban beauty, realistic style, high quality, detailed city landscape, night city, neon lighting, urban nightlife, metropolitan night', '城市,夜景,霓虹,通用'),
('田园风光', 'placeholder://general/countryside.jpg', 'general', '田园风光，宁静致远', 'Countryside scene, rural landscape, peaceful atmosphere, countryside setting, rural beauty, realistic style, high quality, detailed countryside landscape, rural environment, natural lighting, peaceful countryside, rural scenery', '田园,乡村,宁静,通用'),
('雨夜街景', 'placeholder://general/rainy_night_street.jpg', 'general', '雨夜街景，诗意氛围', 'Rainy night street scene, wet streets, atmospheric mood, urban setting, poetic atmosphere, realistic style, high quality, detailed street landscape, rainy environment, dramatic lighting, poetic moment, urban atmosphere', '雨夜,街景,诗意,通用'),
('晨曦微光', 'placeholder://general/dawn_light.jpg', 'general', '晨曦微光，新的一天', 'Dawn light scene, morning light, fresh atmosphere, natural setting, new beginning, realistic style, high quality, detailed dawn landscape, morning environment, soft morning lighting, new day, morning beauty', '晨曦,微光,清晨,通用'),
('黄昏余晖', 'placeholder://general/dusk_glow.jpg', 'general', '黄昏余晖，温暖时光', 'Dusk glow scene, evening light, warm atmosphere, natural setting, evening beauty, realistic style, high quality, detailed dusk landscape, evening environment, warm golden lighting, evening moment, sunset beauty', '黄昏,余晖,温暖,通用'),
('雪景如画', 'placeholder://general/snow_scene.jpg', 'general', '雪景如画，纯净世界', 'Snow scene, winter landscape, pure atmosphere, winter setting, winter beauty, realistic style, high quality, detailed snow landscape, winter environment, soft winter lighting, pure world, winter scenery', '雪景,冬天,纯净,通用'),
('花海盛开', 'placeholder://general/flower_sea.jpg', 'general', '花海盛开，绚烂多彩', 'Flower sea scene, blooming flowers, vibrant atmosphere, garden setting, floral beauty, realistic style, high quality, detailed flower landscape, garden environment, bright natural lighting, colorful world, floral scenery', '花海,花朵,绚烂,通用');

