-- 更新资源提示词，添加中国元素
-- 排除已有中国元素的资源，以及特定国外IP的资源（日本、埃及、希腊、欧洲、文艺复兴等）

-- ========== 头像类别 (Avatar) ==========
-- 现实风格头像 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A gentle and cute Chinese girl portrait, soft features, warm smile, natural lighting, realistic style, high quality, detailed facial features, peaceful expression, modern Chinese clothing with traditional elements, Chinese aesthetic, studio portrait photography' WHERE `name` = '温柔少女' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A sunny and cheerful Chinese boy portrait, bright smile, energetic expression, natural outdoor lighting, realistic style, high quality, detailed facial features, modern casual clothing with Chinese style, Chinese youth culture, vibrant colors, portrait photography' WHERE `name` = '阳光少年' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A mature and elegant Chinese woman portrait, professional appearance, confident expression, soft studio lighting, realistic style, high quality, detailed facial features, business attire with Chinese elements, Chinese professional aesthetic, sophisticated look, portrait photography' WHERE `name` = '成熟女性' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A professional Chinese business man portrait, formal attire with Chinese style, confident expression, professional lighting, realistic style, high quality, detailed facial features, suit with traditional Chinese elements, Chinese business culture, serious expression, corporate portrait photography' WHERE `name` = '商务男士' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'An artistic Chinese youth portrait, creative style, thoughtful expression, soft natural lighting, realistic style, high quality, detailed facial features, casual artistic clothing with Chinese elements, Chinese bohemian style, Chinese artistic culture, artistic portrait photography' WHERE `name` = '文艺青年' AND `category` = 'avatar';

-- 奇幻风格头像 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A magical Chinese girl portrait, fantasy style with Chinese elements, sparkling magical effects, traditional Chinese aesthetics, ethereal lighting, Chinese fantasy art style, high quality, detailed facial features, magical costume with Chinese design, glowing eyes, Chinese fantasy art, vibrant colors' WHERE `name` = '魔法少女' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese fantasy prince portrait, fantasy style with Chinese mythology elements, elegant appearance, mystical lighting, Chinese fantasy art style, high quality, detailed facial features, Chinese fantasy clothing, magical aura, Chinese fantasy character art' WHERE `name` = '精灵王子' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A cyberpunk Chinese girl portrait, futuristic style with Chinese elements, neon lighting with Chinese characters, cybernetic enhancements, dark urban atmosphere in Chinese city, cyberpunk art style, high quality, detailed facial features, futuristic clothing with Chinese design, neon colors, Chinese sci-fi portrait' WHERE `name` = '赛博朋克少女' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese mecha warrior portrait, sci-fi style with Chinese design elements, mechanical armor with Chinese aesthetics, high-tech appearance, dramatic lighting, Chinese sci-fi art style, high quality, detailed mechanical features, futuristic combat suit with Chinese style, technological details, Chinese science fiction art' WHERE `name` = '机甲战士' AND `category` = 'avatar';

-- 其他风格头像 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A mysterious masked Chinese portrait, enigmatic style with Chinese mask design, ornate traditional Chinese mask, mysterious atmosphere, dramatic shadows, Chinese fantasy art style, high quality, detailed mask design, elegant Chinese clothing, mysterious aura, Chinese gothic art style' WHERE `name` = '神秘面具' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese fairy tale princess portrait, fantasy style with Chinese elements, elegant dress with Chinese design, crown, magical atmosphere, soft dreamy lighting, Chinese fantasy art style, high quality, detailed facial features, princess costume with Chinese aesthetics, enchanting expression, Chinese fairy tale art' WHERE `name` = '童话公主' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese rock star portrait, edgy style with Chinese elements, bold expression, dramatic lighting, high contrast, realistic style, high quality, detailed facial features, rock music clothing with Chinese style, rebellious look, Chinese music portrait photography' WHERE `name` = '摇滚歌手' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese yoga teacher portrait, peaceful style, serene expression, natural lighting, Chinese zen atmosphere, realistic style, high quality, detailed facial features, yoga clothing with Chinese elements, calm expression, Chinese wellness portrait photography' WHERE `name` = '瑜伽导师' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese barista portrait, professional style, focused expression, warm cafe lighting, cozy Chinese cafe atmosphere, realistic style, high quality, detailed facial features, cafe uniform, friendly expression, Chinese professional portrait photography' WHERE `name` = '咖啡师' AND `category` = 'avatar';
UPDATE `system_resources` SET `prompt` = 'A Chinese traveler portrait, adventurous style, free-spirited expression, natural outdoor lighting, travel atmosphere in Chinese setting, realistic style, high quality, detailed facial features, travel clothing, wanderlust expression, Chinese travel photography' WHERE `name` = '旅行者' AND `category` = 'avatar';

-- ========== 时代类别 (Era) ==========
-- 现实时代 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A Chinese university campus scene, modern buildings with Chinese architecture, Chinese students walking, green lawns, academic atmosphere, realistic style, high quality, detailed architecture, vibrant Chinese campus life, educational environment, contemporary photography, warm daylight' WHERE `name` = '我的大学' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'A Chinese high school scene, school building with Chinese style, Chinese students in uniform, playground, youthful atmosphere, realistic style, high quality, detailed school environment, Chinese teenage life, educational setting, contemporary photography, bright daylight' WHERE `name` = '我的中学' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'A modern Chinese office workplace, professional environment with Chinese elements, business setting, contemporary Chinese architecture, work atmosphere, realistic style, high quality, detailed office interior, professional setting, Chinese corporate environment, modern photography, office lighting' WHERE `name` = '我的工作' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood scene, playground with Chinese elements, toys, Chinese children playing, nostalgic atmosphere, realistic style, high quality, detailed childhood environment, innocent Chinese memories, playful setting, nostalgic photography, warm golden hour' WHERE `name` = '我的童年' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'A Chinese hometown scene, traditional Chinese architecture, local Chinese streets, hometown atmosphere, nostalgic feeling, realistic style, high quality, detailed hometown environment, familiar Chinese places, Chinese local culture, nostalgic photography, warm lighting' WHERE `name` = '我的故乡' AND `category` = 'era';

-- 虚幻时代 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'Future Chinese world scene, futuristic Chinese city, advanced technology, flying vehicles, sci-fi atmosphere with Chinese elements, sci-fi art style, high quality, detailed futuristic Chinese architecture, high-tech Chinese environment, Chinese science fiction art, neon lighting, futuristic Chinese vision' WHERE `name` = '未来世界' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'Cyberpunk Chinese city scene, neon-lit streets with Chinese characters, futuristic Chinese buildings, cyberpunk atmosphere, dark urban setting in Chinese metropolis, cyberpunk art style, high quality, detailed cyberpunk architecture with Chinese elements, neon colors, Chinese sci-fi art, dramatic neon lighting, dystopian Chinese future' WHERE `name` = '赛博朋克都市' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'Chinese magic world scene, fantasy landscape with Chinese mythology, magical creatures from Chinese legends, floating islands, mystical atmosphere, Chinese fantasy art style, high quality, detailed fantasy environment with Chinese elements, magical elements, Chinese fantasy art, ethereal lighting, enchanted Chinese realm' WHERE `name` = '魔法世界' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'Chinese fairy tale world scene, enchanted forest with Chinese elements, magical Chinese castles, talking animals, Chinese fairy tale characters, whimsical atmosphere, Chinese fantasy art style, high quality, detailed fairy tale environment with Chinese design, storybook setting, dreamy lighting, magical Chinese kingdom, colorful and vibrant, Chinese children''s story illustration style, Chinese fantasy landscape, enchanted realm' WHERE `name` = '童话世界' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'Chinese steampunk era scene, Victorian architecture with Chinese elements and gears, steam-powered machines with Chinese design, brass and copper, industrial atmosphere, Chinese steampunk art style, high quality, detailed steampunk machinery with Chinese aesthetics, mechanical aesthetics, Chinese steampunk art, warm industrial lighting, Chinese retro-futuristic' WHERE `name` = '蒸汽朋克' AND `category` = 'era';
UPDATE `system_resources` SET `prompt` = 'Post-apocalyptic Chinese wasteland scene, ruined Chinese buildings, desolate landscape, survival atmosphere, dystopian setting in Chinese context, post-apocalyptic art style, high quality, detailed wasteland environment, apocalyptic Chinese ruins, Chinese sci-fi art, harsh lighting, survival Chinese world' WHERE `name` = '废土世界' AND `category` = 'era';

-- ========== 角色类别 (Character) ==========
-- 现实时代角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A Chinese university roommate character, Chinese college student, friendly appearance, casual clothing, youthful atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, warm lighting, Chinese college life' WHERE `name` = '大学室友' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese university professor character, scholarly appearance, professional attire, intellectual atmosphere, realistic style, high quality, detailed character design, Chinese academic setting, professional portrait, natural lighting, Chinese educational environment' WHERE `name` = '大学导师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese university classmate character, Chinese college student, friendly appearance, casual clothing, collaborative atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, natural lighting, Chinese college life' WHERE `name` = '大学同学' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese university senior student character, older student, experienced appearance, casual clothing, mentoring atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, warm lighting, Chinese college guidance' WHERE `name` = '大学学长' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese university club member character, Chinese college student, enthusiastic appearance, casual clothing, passionate atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, vibrant lighting, Chinese college activities' WHERE `name` = '大学社团伙伴' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A gentle Chinese junior sister character, Chinese female college student, soft appearance, cute clothing, gentle expression, innocent atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, soft lighting, Chinese college life' WHERE `name` = '温柔学妹' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'An intellectual Chinese senior sister character, Chinese female college student, elegant appearance, sophisticated clothing, wise expression, mature atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, warm lighting, Chinese college life' WHERE `name` = '知性学姐' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A handsome Chinese senior character, Chinese male college student, attractive appearance, stylish clothing, confident expression, sunny atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, bright lighting, Chinese college life' WHERE `name` = '帅气学长' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'An artistic Chinese youth character, Chinese college student, creative appearance, bohemian clothing with Chinese elements, thoughtful expression, artistic atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, soft lighting, Chinese college life' WHERE `name` = '文艺青年' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'An athletic Chinese student character, Chinese college student, fit appearance, sports clothing, energetic expression, active atmosphere, realistic style, high quality, detailed character design, modern Chinese setting, contemporary portrait, bright lighting, Chinese college life' WHERE `name` = '运动健将' AND `category` = 'character';

-- 中学角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A Chinese high school desk mate character, Chinese teenager, Chinese school uniform, innocent expression, youthful atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, bright lighting, Chinese school life' WHERE `name` = '中学同桌' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese high school teacher character, Chinese educator, professional appearance, formal clothing, nurturing atmosphere, realistic style, high quality, detailed character design, Chinese school setting, professional portrait, natural lighting, Chinese educational guidance' WHERE `name` = '中学老师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese high school monitor character, Chinese student leader, responsible appearance, Chinese school uniform, leadership atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, bright lighting, Chinese student leadership' WHERE `name` = '中学班长' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese high school friend character, Chinese teenager, casual appearance, Chinese school uniform, friendly atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, warm lighting, Chinese teenage friendship' WHERE `name` = '中学好友' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese high school sports buddy character, Chinese athlete, energetic appearance, Chinese sports uniform, active atmosphere, realistic style, high quality, detailed character design, Chinese school setting, athletic portrait, bright lighting, Chinese sports activities' WHERE `name` = '中学运动伙伴' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A gentle Chinese desk mate character, Chinese female high school student, soft appearance, Chinese school uniform, gentle expression, quiet atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, soft lighting, Chinese school life' WHERE `name` = '温柔同桌' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A sunny Chinese boy character, Chinese male high school student, bright appearance, Chinese school uniform, cheerful expression, energetic atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, bright lighting, Chinese school life' WHERE `name` = '阳光少年' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A study monitor character, Chinese female high school student, intelligent appearance, Chinese school uniform, confident expression, academic atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, bright lighting, Chinese school life' WHERE `name` = '学霸班长' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A cheerful Chinese junior character, Chinese female high school student, cute appearance, Chinese school uniform, lively expression, energetic atmosphere, realistic style, high quality, detailed character design, Chinese school setting, teenage portrait, bright lighting, Chinese school life' WHERE `name` = '活泼学妹' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'An athletic Chinese student character, Chinese male high school student, fit appearance, Chinese sports uniform, determined expression, athletic atmosphere, realistic style, high quality, detailed character design, Chinese school setting, athletic portrait, bright lighting, Chinese sports activities' WHERE `name` = '运动健将' AND `category` = 'character';

-- 职场角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace colleague character, Chinese professional appearance, business attire, friendly expression, professional atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, office lighting, Chinese work environment' WHERE `name` = '职场同事' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace boss character, Chinese executive appearance, formal business attire, authoritative expression, leadership atmosphere, realistic style, high quality, detailed character design, Chinese office setting, executive portrait, professional lighting, Chinese corporate leadership' WHERE `name` = '职场上司' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace newcomer character, Chinese young professional, eager appearance, business attire, enthusiastic expression, learning atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, bright lighting, Chinese career start' WHERE `name` = '职场新人' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace mentor character, Chinese experienced professional, wise appearance, business attire, guiding expression, mentoring atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, warm lighting, Chinese career guidance' WHERE `name` = '职场导师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace partner character, Chinese professional appearance, business attire, collaborative expression, partnership atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, professional lighting, Chinese business collaboration' WHERE `name` = '职场合作伙伴' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'An intellectual Chinese female boss character, Chinese professional woman, elegant appearance, business attire, confident expression, leadership atmosphere, realistic style, high quality, detailed character design, Chinese office setting, executive portrait, professional lighting, Chinese corporate leadership' WHERE `name` = '知性女上司' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A gentle Chinese female colleague character, Chinese professional woman, soft appearance, business attire, friendly expression, warm atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, warm lighting, Chinese work environment' WHERE `name` = '温柔女同事' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A handsome Chinese male boss character, Chinese professional man, attractive appearance, business attire, confident expression, leadership atmosphere, realistic style, high quality, detailed character design, Chinese office setting, executive portrait, professional lighting, Chinese corporate leadership' WHERE `name` = '帅气男上司' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace newcomer character, Chinese young professional woman, gentle appearance, business attire, eager expression, learning atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, bright lighting, Chinese career start' WHERE `name` = '职场新人女' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace newcomer character, Chinese young professional man, bright appearance, business attire, enthusiastic expression, learning atmosphere, realistic style, high quality, detailed character design, Chinese office setting, professional portrait, bright lighting, Chinese career start' WHERE `name` = '职场新人男' AND `category` = 'character';

-- 童年角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood friend character, Chinese child, playful appearance, casual clothing, innocent atmosphere, realistic style, high quality, detailed character design, Chinese childhood setting, nostalgic portrait, warm lighting, Chinese childhood memories' WHERE `name` = '童年玩伴' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood neighbor character, Chinese friendly adult or child, warm appearance, casual clothing, neighborly atmosphere, realistic style, high quality, detailed character design, Chinese neighborhood setting, nostalgic portrait, warm lighting, Chinese childhood community' WHERE `name` = '童年邻居' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood teacher character, Chinese elementary teacher, kind appearance, casual clothing, nurturing expression, educational atmosphere, realistic style, high quality, detailed character design, Chinese school setting, nostalgic portrait, warm lighting, Chinese childhood education' WHERE `name` = '童年老师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood elder character, Chinese grandparent or older relative, wise appearance, traditional Chinese clothing, loving expression, caring atmosphere, realistic style, high quality, detailed character design, Chinese home setting, nostalgic portrait, warm lighting, Chinese family care' WHERE `name` = '童年长辈' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A Chinese childhood pet character, Chinese dog or cat, cute appearance, playful expression, loyal atmosphere, realistic style, high quality, detailed character design, Chinese home setting, nostalgic portrait, warm lighting, Chinese childhood companion' WHERE `name` = '童年宠物' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A gentle Chinese little girl character, Chinese young girl, soft appearance, cute clothing, innocent expression, pure atmosphere, realistic style, high quality, detailed character design, Chinese childhood setting, nostalgic portrait, warm lighting, Chinese childhood memories' WHERE `name` = '温柔小女孩' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A cheerful Chinese little boy character, Chinese young boy, bright appearance, casual clothing, playful expression, energetic atmosphere, realistic style, high quality, detailed character design, Chinese childhood setting, nostalgic portrait, warm lighting, Chinese childhood memories' WHERE `name` = '活泼小男孩' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A gentle Chinese female teacher character, Chinese elementary teacher, soft appearance, casual clothing, kind expression, nurturing atmosphere, realistic style, high quality, detailed character design, Chinese school setting, nostalgic portrait, warm lighting, Chinese childhood education' WHERE `name` = '温柔女老师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A kind Chinese grandmother character, Chinese elderly woman, warm appearance, traditional Chinese clothing, loving expression, caring atmosphere, realistic style, high quality, detailed character design, Chinese home setting, nostalgic portrait, warm lighting, Chinese family care' WHERE `name` = '慈祥奶奶' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'A kind Chinese grandfather character, Chinese elderly man, warm appearance, traditional Chinese clothing, friendly expression, caring atmosphere, realistic style, high quality, detailed character design, Chinese home setting, nostalgic portrait, warm lighting, Chinese family care' WHERE `name` = '和蔼爷爷' AND `category` = 'character';

-- 故乡角色 - 已有中国元素，无需更新

-- 虚幻时代角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'Future Chinese warrior character, sci-fi style with Chinese design, advanced combat armor with Chinese elements, high-tech weapons, determined expression, futuristic atmosphere, Chinese sci-fi art style, high quality, detailed character design, futuristic Chinese setting, sci-fi portrait, neon lighting, Chinese future soldier' WHERE `name` = '未来战士' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese AI assistant character, sci-fi style with Chinese design, holographic appearance, digital effects with Chinese elements, friendly expression, technological atmosphere, Chinese sci-fi art style, high quality, detailed character design, futuristic Chinese setting, digital portrait, blue lighting, Chinese artificial intelligence' WHERE `name` = 'AI助手' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese space explorer character, sci-fi style with Chinese design, space suit, advanced equipment, adventurous expression, space atmosphere, Chinese sci-fi art style, high quality, detailed character design, space setting, Chinese astronaut portrait, cosmic lighting, Chinese space adventurer' WHERE `name` = '太空探索者' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Future Chinese scientist character, sci-fi style with Chinese design, lab coat, advanced technology, intelligent expression, scientific atmosphere, Chinese sci-fi art style, high quality, detailed character design, futuristic Chinese lab setting, scientist portrait, bright lighting, Chinese scientific innovation' WHERE `name` = '未来科学家' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Future Chinese engineer character, sci-fi style with Chinese design, technical gear, advanced tools, focused expression, technological atmosphere, Chinese sci-fi art style, high quality, detailed character design, futuristic Chinese workshop setting, engineer portrait, industrial lighting, Chinese technical expertise' WHERE `name` = '未来工程师' AND `category` = 'character';

-- 魔法世界角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'Chinese mage character, fantasy style with Chinese elements, Chinese wizard robes, magical staff, mystical expression, magical atmosphere, Chinese fantasy art style, high quality, detailed character design, Chinese fantasy setting, wizard portrait, magical lighting, powerful Chinese mage' WHERE `name` = '魔法师' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese archer character, fantasy style with Chinese mythology, elegant Chinese clothing, bow and arrow, graceful expression, fantasy atmosphere, Chinese fantasy art style, high quality, detailed character design, Chinese fantasy setting, archer portrait, ethereal lighting, skilled Chinese archer' WHERE `name` = '精灵弓箭手' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese dragon knight character, fantasy style with Chinese elements, Chinese knight armor, dragon companion, heroic expression, epic atmosphere, Chinese fantasy art style, high quality, detailed character design, Chinese fantasy setting, knight portrait, dramatic lighting, legendary Chinese rider' WHERE `name` = '龙骑士' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese magic apprentice character, fantasy style with Chinese elements, simple Chinese robes, beginner staff, eager expression, learning atmosphere, Chinese fantasy art style, high quality, detailed character design, Chinese fantasy setting, apprentice portrait, soft lighting, young Chinese mage' WHERE `name` = '魔法学徒' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese mage character, fantasy style with Chinese elements, elegant Chinese robes, nature staff, graceful expression, fantasy atmosphere, Chinese fantasy art style, high quality, detailed character design, Chinese fantasy setting, Chinese mage portrait, ethereal lighting, Chinese nature magic' WHERE `name` = '精灵法师' AND `category` = 'character';

-- 赛博朋克角色 - 添加中国元素
UPDATE `system_resources` SET `prompt` = 'Chinese cyber hacker character, cyberpunk style with Chinese elements, cybernetic enhancements, digital interface with Chinese characters, tech-savvy expression, cyberpunk atmosphere, Chinese cyberpunk art style, high quality, detailed character design, Chinese cyberpunk setting, hacker portrait, neon lighting, Chinese digital outlaw' WHERE `name` = '赛博黑客' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese cyborg character, cyberpunk style with Chinese elements, mechanical parts, human-robot fusion, determined expression, cyberpunk atmosphere, Chinese cyberpunk art style, high quality, detailed character design, Chinese cyberpunk setting, cyborg portrait, neon lighting, Chinese enhanced human' WHERE `name` = '义体改造人' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese cyber cop character, cyberpunk style with Chinese elements, law enforcement gear, cybernetic enhancements, authoritative expression, cyberpunk atmosphere, Chinese cyberpunk art style, high quality, detailed character design, Chinese cyberpunk setting, police portrait, neon lighting, Chinese law enforcement' WHERE `name` = '赛博警察' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese cyber merchant character, cyberpunk style with Chinese elements, business attire, digital interface, shrewd expression, cyberpunk atmosphere, Chinese cyberpunk art style, high quality, detailed character design, Chinese cyberpunk setting, merchant portrait, neon lighting, Chinese business elite' WHERE `name` = '赛博商人' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese cyber doctor character, cyberpunk style with Chinese elements, medical gear, cybernetic tools, professional expression, cyberpunk atmosphere, Chinese cyberpunk art style, high quality, detailed character design, Chinese cyberpunk clinic setting, doctor portrait, neon lighting, Chinese cybernetic medicine' WHERE `name` = '赛博医生' AND `category` = 'character';

-- 童话角色 - 小红帽和灰姑娘是西方童话，但可以添加中国元素
UPDATE `system_resources` SET `prompt` = 'Chinese little red riding hood character, Chinese young girl appearance, red hood with Chinese design, basket, innocent yet brave expression, Chinese fairy tale atmosphere, Chinese children''s story illustration style, high quality, detailed character design, Chinese fairy tale setting, little girl portrait, forest lighting, brave Chinese girl, Chinese storybook style, classic character' WHERE `name` = '小红帽' AND `category` = 'character';
UPDATE `system_resources` SET `prompt` = 'Chinese cinderella character, Chinese beautiful young woman appearance, simple dress transforming to ball gown with Chinese design, glass slippers, kind expression, Chinese fairy tale atmosphere, Chinese children''s story illustration style, high quality, detailed character design, Chinese fairy tale setting, cinderella portrait, magical lighting, kind-hearted Chinese girl, Chinese storybook style, classic princess' WHERE `name` = '灰姑娘' AND `category` = 'character';

-- ========== 剧本类别 (Scenario) ==========
UPDATE `system_resources` SET `prompt` = 'A Chinese campus youth drama scene, Chinese school setting, Chinese students, youthful atmosphere, emotional moments, realistic style, high quality, detailed Chinese school environment, Chinese teenage life, dramatic composition, natural lighting, Chinese coming-of-age story, emotional depth' WHERE `name` = '校园青春剧' AND `category` = 'scenario';
UPDATE `system_resources` SET `prompt` = 'A Chinese workplace struggle drama scene, Chinese office setting, Chinese professionals, business atmosphere, career challenges, realistic style, high quality, detailed Chinese office environment, Chinese professional life, dramatic composition, office lighting, Chinese career story, personal growth' WHERE `name` = '职场奋斗剧' AND `category` = 'scenario';
UPDATE `system_resources` SET `prompt` = 'A sci-fi adventure drama scene, futuristic Chinese setting, Chinese space explorers, technological atmosphere, adventure elements, Chinese sci-fi art style, high quality, detailed futuristic Chinese environment, Chinese space age, dynamic composition, neon lighting, Chinese space adventure, technological wonder' WHERE `name` = '科幻冒险剧' AND `category` = 'scenario';
UPDATE `system_resources` SET `prompt` = 'A fantasy magic drama scene, magical Chinese setting, Chinese wizards and creatures, mystical atmosphere, magical elements, Chinese fantasy art style, high quality, detailed fantasy environment with Chinese elements, magical Chinese realm, epic composition, magical lighting, Chinese fantasy adventure, enchanted world' WHERE `name` = '奇幻魔法剧' AND `category` = 'scenario';
UPDATE `system_resources` SET `prompt` = 'A mystery thriller drama scene, mysterious Chinese setting, Chinese detectives, suspenseful atmosphere, mystery elements, Chinese noir style, high quality, detailed mysterious Chinese environment, Chinese crime scene, dramatic composition, dramatic shadows, Chinese mystery story, suspenseful plot' WHERE `name` = '悬疑推理剧' AND `category` = 'scenario';
UPDATE `system_resources` SET `prompt` = 'A romance drama scene, romantic Chinese setting, Chinese couples, emotional atmosphere, love story elements, realistic style, high quality, detailed romantic Chinese environment, Chinese relationship dynamics, emotional composition, soft lighting, Chinese love story, romantic moments' WHERE `name` = '爱情浪漫剧' AND `category` = 'scenario';

-- ========== 日记类别 (Journal) ==========
UPDATE `system_resources` SET `prompt` = 'A Chinese morning journal scene, Chinese sunrise, peaceful morning atmosphere, Chinese journal book, pen, soft morning light, realistic style, high quality, detailed Chinese journal setting, Chinese morning routine, warm lighting, new day beginning, peaceful Chinese moment' WHERE `name` = '晨间日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese night reflection journal scene, Chinese moonlit night, quiet atmosphere, Chinese journal book, candlelight, peaceful evening, realistic style, high quality, detailed Chinese journal setting, Chinese evening routine, soft candlelight, daily Chinese reflection, quiet moment' WHERE `name` = '夜晚反思' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese work record journal scene, Chinese office setting, professional atmosphere, Chinese journal book, work notes, Chinese business environment, realistic style, high quality, detailed Chinese journal setting, Chinese workplace, office lighting, Chinese work documentation, professional record' WHERE `name` = '工作记录' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese study notes journal scene, Chinese study room, academic atmosphere, Chinese journal book, study materials, Chinese educational setting, realistic style, high quality, detailed Chinese journal setting, Chinese learning environment, natural lighting, Chinese study documentation, knowledge accumulation' WHERE `name` = '学习笔记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese travel diary scene, Chinese travel setting, adventurous atmosphere, Chinese journal book, travel souvenirs, Chinese location, realistic style, high quality, detailed Chinese journal setting, Chinese travel environment, natural lighting, Chinese travel documentation, adventure record' WHERE `name` = '旅行日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese mood journal scene, emotional Chinese setting, personal atmosphere, Chinese journal book, emotional expression, intimate Chinese space, realistic style, high quality, detailed Chinese journal setting, Chinese personal space, soft lighting, Chinese emotional documentation, personal reflection' WHERE `name` = '心情日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese gratitude journal scene, warm Chinese setting, positive atmosphere, Chinese journal book, thankful elements, cozy Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese positive space, warm lighting, Chinese gratitude documentation, positive reflection' WHERE `name` = '感恩日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese dream journal scene, inspirational Chinese setting, hopeful atmosphere, Chinese journal book, dream elements, inspiring Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese dream space, bright lighting, Chinese dream documentation, future planning' WHERE `name` = '梦想日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese reading notes journal scene, Chinese library setting, literary atmosphere, Chinese journal book, Chinese books, Chinese reading environment, realistic style, high quality, detailed Chinese journal setting, Chinese reading space, natural lighting, Chinese reading documentation, Chinese literary reflection' WHERE `name` = '读书笔记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese food diary scene, Chinese kitchen setting, Chinese culinary atmosphere, Chinese journal book, Chinese food elements, Chinese cooking environment, realistic style, high quality, detailed Chinese journal setting, Chinese culinary space, warm lighting, Chinese food documentation, Chinese culinary memory' WHERE `name` = '美食日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese fitness journal scene, Chinese gym setting, active atmosphere, Chinese journal book, fitness equipment, Chinese sports environment, realistic style, high quality, detailed Chinese journal setting, Chinese fitness space, bright lighting, Chinese fitness documentation, Chinese health record' WHERE `name` = '运动日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese art journal scene, Chinese studio setting, creative atmosphere, Chinese journal book, Chinese art supplies, Chinese artistic environment, realistic style, high quality, detailed Chinese journal setting, Chinese creative space, studio lighting, Chinese art documentation, Chinese creative expression' WHERE `name` = '艺术日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese dream record journal scene, mystical Chinese setting, dreamy atmosphere, Chinese journal book, dream elements, Chinese surreal environment, Chinese fantasy art style, high quality, detailed Chinese journal setting, Chinese dream space, ethereal lighting, Chinese dream documentation, Chinese subconscious exploration' WHERE `name` = '梦境记录' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese inspiration capture journal scene, creative Chinese setting, inspiring atmosphere, Chinese journal book, creative elements, inspiring Chinese environment, Chinese artistic style, high quality, detailed Chinese journal setting, Chinese creative space, bright lighting, Chinese inspiration documentation, Chinese idea collection' WHERE `name` = '灵感捕捉' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese growth record journal scene, personal Chinese setting, reflective atmosphere, Chinese journal book, growth elements, Chinese personal space, realistic style, high quality, detailed Chinese journal setting, Chinese personal environment, natural lighting, Chinese growth documentation, Chinese life journey' WHERE `name` = '成长记录' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese memoir journal scene, nostalgic Chinese setting, memory atmosphere, Chinese journal book, old Chinese photos, nostalgic Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese memory space, warm lighting, Chinese memory documentation, Chinese past memories' WHERE `name` = '回忆录' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese observation journal scene, detailed Chinese setting, observant atmosphere, Chinese journal book, observation tools, detailed Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese observation space, natural lighting, Chinese observation documentation, Chinese detail recording' WHERE `name` = '观察日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese thinking journal scene, contemplative Chinese setting, thoughtful atmosphere, Chinese journal book, thinking elements, quiet Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese thinking space, soft lighting, Chinese thinking documentation, Chinese deep reflection' WHERE `name` = '思考日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese planning journal scene, organized Chinese setting, planning atmosphere, Chinese journal book, planning tools, organized Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese planning space, bright lighting, Chinese planning documentation, Chinese goal setting' WHERE `name` = '计划日记' AND `category` = 'journal';
UPDATE `system_resources` SET `prompt` = 'A Chinese summary journal scene, reflective Chinese setting, summary atmosphere, Chinese journal book, summary elements, reflective Chinese environment, realistic style, high quality, detailed Chinese journal setting, Chinese reflection space, natural lighting, Chinese summary documentation, Chinese review and reflection' WHERE `name` = '总结日记' AND `category` = 'journal';

-- ========== 通用类别 (General) ==========
UPDATE `system_resources` SET `prompt` = 'Chinese mountains and rivers landscape, natural Chinese scenery, flowing water, Chinese mountain peaks, natural beauty, realistic style, high quality, detailed Chinese natural environment, scenic Chinese landscape, natural lighting, peaceful Chinese nature, majestic Chinese scenery' WHERE `name` = '山川河流' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Secret Chinese forest scene, dense trees, mysterious atmosphere, Chinese natural setting, Chinese forest environment, realistic style, high quality, detailed Chinese forest landscape, mystical Chinese nature, dappled lighting, enchanted Chinese forest, Chinese natural mystery' WHERE `name` = '森林秘境' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese beach sunset scene, Chinese ocean, golden hour, romantic atmosphere, Chinese coastal setting, realistic style, high quality, detailed Chinese beach landscape, Chinese sunset beauty, warm golden lighting, romantic Chinese moment, Chinese coastal scenery' WHERE `name` = '海边日落' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese starry night scene, starry Chinese sky, night atmosphere, Chinese cosmic setting, astronomical beauty, realistic style, high quality, detailed Chinese night sky, starry Chinese landscape, dark night lighting, Chinese cosmic wonder, Chinese astronomical scene' WHERE `name` = '星空夜晚' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Modern Chinese city scene, Chinese skyscrapers, urban atmosphere, contemporary Chinese architecture, Chinese city setting, realistic style, high quality, detailed Chinese urban landscape, modern Chinese architecture, city lighting, Chinese urban life, Chinese metropolitan scene' WHERE `name` = '现代都市' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Time passing concept with Chinese elements, Chinese clock elements, temporal atmosphere, Chinese abstract setting, time concept, Chinese abstract art style, high quality, detailed abstract composition, Chinese time symbolism, dramatic lighting, Chinese temporal flow, Chinese conceptual art' WHERE `name` = '时间流逝' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Dream flying concept with Chinese elements, Chinese wings, freedom atmosphere, inspirational Chinese setting, dream concept, Chinese fantasy art style, high quality, detailed abstract composition, Chinese freedom symbolism, ethereal lighting, Chinese dream flight, Chinese inspirational art' WHERE `name` = '梦想飞翔' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Light of hope concept with Chinese elements, Chinese light rays, hopeful atmosphere, inspirational Chinese setting, hope concept, Chinese abstract art style, high quality, detailed abstract composition, Chinese hope symbolism, bright lighting, Chinese hopeful future, Chinese inspirational art' WHERE `name` = '希望之光' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese book stack scene, Chinese books, Chinese literary atmosphere, Chinese library setting, Chinese knowledge concept, realistic style, high quality, detailed Chinese book composition, Chinese literary environment, warm lighting, Chinese knowledge collection, Chinese reading scene' WHERE `name` = '书籍堆叠' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese coffee time scene, Chinese coffee cup, cozy Chinese atmosphere, Chinese cafe setting, relaxation concept, realistic style, high quality, detailed Chinese cafe composition, cozy Chinese environment, warm lighting, relaxing Chinese moment, Chinese cafe scene' WHERE `name` = '咖啡时光' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese music melody concept, Chinese musical instruments, artistic Chinese atmosphere, Chinese music setting, Chinese art concept, Chinese abstract art style, high quality, detailed Chinese musical composition, Chinese artistic environment, dramatic lighting, Chinese musical beauty, Chinese artistic scene' WHERE `name` = '音乐旋律' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Four seasons transformation in Chinese style, Chinese seasonal elements, temporal atmosphere, Chinese nature setting, time concept, realistic style, high quality, detailed Chinese seasonal composition, Chinese natural environment, seasonal lighting, Chinese time flow, Chinese seasonal beauty' WHERE `name` = '四季变换' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese city night scene, Chinese urban lights, night atmosphere, Chinese city setting, Chinese urban beauty, realistic style, high quality, detailed Chinese city landscape, Chinese night city, neon lighting, Chinese urban nightlife, Chinese metropolitan night' WHERE `name` = '城市夜景' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese countryside scene, Chinese rural landscape, peaceful atmosphere, Chinese countryside setting, Chinese rural beauty, realistic style, high quality, detailed Chinese countryside landscape, Chinese rural environment, natural lighting, peaceful Chinese countryside, Chinese rural scenery' WHERE `name` = '田园风光' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese rainy night street scene, wet Chinese streets, atmospheric mood, Chinese urban setting, Chinese poetic atmosphere, realistic style, high quality, detailed Chinese street landscape, Chinese rainy environment, dramatic lighting, Chinese poetic moment, Chinese urban atmosphere' WHERE `name` = '雨夜街景' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese dawn light scene, Chinese morning light, fresh atmosphere, Chinese natural setting, new beginning, realistic style, high quality, detailed Chinese dawn landscape, Chinese morning environment, soft morning lighting, new Chinese day, Chinese morning beauty' WHERE `name` = '晨曦微光' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese dusk glow scene, Chinese evening light, warm atmosphere, Chinese natural setting, Chinese evening beauty, realistic style, high quality, detailed Chinese dusk landscape, Chinese evening environment, warm golden lighting, Chinese evening moment, Chinese sunset beauty' WHERE `name` = '黄昏余晖' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese snow scene, Chinese winter landscape, pure atmosphere, Chinese winter setting, Chinese winter beauty, realistic style, high quality, detailed Chinese snow landscape, Chinese winter environment, soft winter lighting, pure Chinese world, Chinese winter scenery' WHERE `name` = '雪景如画' AND `category` = 'general';
UPDATE `system_resources` SET `prompt` = 'Chinese flower sea scene, blooming Chinese flowers, vibrant atmosphere, Chinese garden setting, Chinese floral beauty, realistic style, high quality, detailed Chinese flower landscape, Chinese garden environment, bright natural lighting, colorful Chinese world, Chinese floral scenery' WHERE `name` = '花海盛开' AND `category` = 'general';




