-- 第五阶段：为世界古代历史场景的物品创建资源记录（包含AI图片生成提示词）
-- 场景：古代埃及、古希腊、中世纪欧洲、文艺复兴、工业革命

SET NAMES utf8mb4;

-- ========== 古代埃及 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('法老权杖（物品）', 'placeholder://item/item_egypt_scepter.jpg', 'item', '象征法老权力的权杖', 'Pharaoh scepter, ancient Egyptian royal scepter, pharaonic staff, golden scepter with hieroglyphs, realistic style, high quality, detailed scepter, ornate Egyptian royal staff, ancient Egyptian artifact with intricate design', '埃及,权杖,物品', NULL, NOW(), NOW()),
('圣甲虫护身符（物品）', 'placeholder://item/item_egypt_scarab.jpg', 'item', '古埃及的圣甲虫护身符', 'Scarab amulet, ancient Egyptian amulet, sacred beetle amulet, gold and lapis lazuli scarab, realistic style, high quality, detailed amulet, ornate Egyptian talisman, ancient Egyptian artifact with hieroglyphic symbols', '埃及,护身符,物品', NULL, NOW(), NOW()),
('莎草纸（物品）', 'placeholder://item/item_egypt_papyrus.jpg', 'item', '记录文字的莎草纸', 'Papyrus scroll, ancient Egyptian document, hieroglyphic scroll, ancient writing material, realistic style, high quality, detailed scroll, ancient Egyptian papyrus with hieroglyphs, historical document appearance', '埃及,文字,物品', NULL, NOW(), NOW()),
('木乃伊面具（物品）', 'placeholder://item/item_egypt_mask.jpg', 'item', '法老的木乃伊面具', 'Mummy mask, pharaoh death mask, ancient Egyptian funerary mask, golden mask with blue details, realistic style, high quality, detailed mask, ornate Egyptian funerary mask, ancient Egyptian artifact with intricate facial features', '埃及,面具,物品', NULL, NOW(), NOW()),
('图坦卡蒙匕首（物品）', 'placeholder://item/item_egypt_dagger.jpg', 'item', '法老的匕首', 'Egyptian dagger, pharaoh dagger, ancient Egyptian blade, ornate ceremonial dagger, realistic style, high quality, detailed dagger, golden Egyptian dagger with gemstones, ancient Egyptian weapon with hieroglyphic decoration', '埃及,武器,物品', NULL, NOW(), NOW()),
('荷鲁斯之眼（物品）', 'placeholder://item/item_egypt_eye.jpg', 'item', '象征保护的荷鲁斯之眼', 'Eye of Horus, ancient Egyptian symbol, protective amulet, sacred Egyptian eye symbol, realistic style, high quality, detailed amulet, ornate Egyptian symbol, ancient Egyptian artifact with protective meaning', '埃及,符号,物品', NULL, NOW(), NOW()),
('尼罗河水（物品）', 'placeholder://item/item_egypt_nile_water.jpg', 'item', '来自尼罗河的神圣之水', 'Nile water, sacred water from Nile River, ancient Egyptian water, ceremonial water container, realistic style, high quality, detailed container, ornate Egyptian water vessel, ancient Egyptian ritual item', '埃及,水,物品', NULL, NOW(), NOW()),
('黄金面具（物品）', 'placeholder://item/item_egypt_gold_mask.jpg', 'item', '法老的黄金面具', 'Gold mask, pharaoh golden mask, ancient Egyptian gold artifact, ornate golden funerary mask, realistic style, high quality, detailed mask, exquisite Egyptian gold mask, ancient Egyptian treasure with precious metal', '埃及,面具,物品', NULL, NOW(), NOW());

-- ========== 古希腊 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('橄榄枝（物品）', 'placeholder://item/item_greece_olive_branch.jpg', 'item', '象征和平的橄榄枝', 'Olive branch, ancient Greek symbol of peace, sacred olive branch, Greek olive wreath, realistic style, high quality, detailed branch, elegant olive branch, ancient Greek symbol with cultural significance', '希腊,橄榄,物品', NULL, NOW(), NOW()),
('陶罐（物品）', 'placeholder://item/item_greece_amphora.jpg', 'item', '古希腊的陶罐', 'Greek amphora, ancient Greek pottery, classical Greek vase, decorated ceramic vessel, realistic style, high quality, detailed pottery, ornate Greek amphora with mythological scenes, ancient Greek artifact with red and black figure painting', '希腊,陶器,物品', NULL, NOW(), NOW()),
('月桂枝冠（物品）', 'placeholder://item/item_greece_laurel.jpg', 'item', '胜利者的月桂枝冠', 'Laurel wreath, ancient Greek victory crown, Olympic laurel crown, golden laurel wreath, realistic style, high quality, detailed wreath, elegant Greek laurel crown, ancient Greek symbol of victory and honor', '希腊,桂冠,物品', NULL, NOW(), NOW()),
('古希腊硬币（物品）', 'placeholder://item/item_greece_coin.jpg', 'item', '古希腊的货币', 'Ancient Greek coin, Greek drachma, classical Greek currency, silver or gold coin with Greek symbols, realistic style, high quality, detailed coin, ornate Greek coin with mythological figures, ancient Greek currency with detailed relief', '希腊,货币,物品', NULL, NOW(), NOW()),
('七弦琴（物品）', 'placeholder://item/item_greece_lyre.jpg', 'item', '古希腊的乐器', 'Greek lyre, ancient Greek musical instrument, classical lyre, ornate stringed instrument, realistic style, high quality, detailed lyre, elegant Greek musical instrument, ancient Greek lyre with decorative elements', '希腊,乐器,物品', NULL, NOW(), NOW()),
('羊皮纸（物品）', 'placeholder://item/item_greece_parchment.jpg', 'item', '记录文字的羊皮纸', 'Parchment, ancient Greek document, classical scroll, Greek manuscript, realistic style, high quality, detailed parchment, ancient Greek writing material, historical document with Greek text', '希腊,文字,物品', NULL, NOW(), NOW()),
('古希腊雕像（物品）', 'placeholder://item/item_greece_statue.jpg', 'item', '精美的古希腊雕像', 'Greek statue, ancient Greek sculpture, classical Greek statue, marble or bronze statue, realistic style, high quality, detailed statue, ornate Greek sculpture, ancient Greek art with detailed craftsmanship', '希腊,雕像,物品', NULL, NOW(), NOW()),
('油灯（物品）', 'placeholder://item/item_greece_lamp.jpg', 'item', '古希腊的油灯', 'Greek oil lamp, ancient Greek lamp, classical lamp, terracotta or bronze lamp, realistic style, high quality, detailed lamp, ornate Greek lamp, ancient Greek lighting device with decorative design', '希腊,灯具,物品', NULL, NOW(), NOW());

-- ========== 中世纪欧洲 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('骑士剑（物品）', 'placeholder://item/item_medieval_sword.jpg', 'item', '骑士使用的长剑', 'Medieval knight sword, longsword, European medieval weapon, ornate knight blade, realistic style, high quality, detailed sword, elegant medieval sword with crossguard, European medieval weapon with detailed hilt', '中世纪,武器,物品', NULL, NOW(), NOW()),
('盾牌（物品）', 'placeholder://item/item_medieval_shield.jpg', 'item', '绘有纹章的盾牌', 'Medieval shield, knight shield, heraldic shield, decorated shield with coat of arms, realistic style, high quality, detailed shield, ornate medieval shield with heraldic symbols, European medieval defensive weapon', '中世纪,盾牌,物品', NULL, NOW(), NOW()),
('十字架（物品）', 'placeholder://item/item_medieval_cross.jpg', 'item', '宗教十字架', 'Medieval cross, Christian cross, ornate religious cross, golden or silver cross, realistic style, high quality, detailed cross, elegant religious cross, medieval religious artifact with intricate design', '中世纪,宗教,物品', NULL, NOW(), NOW()),
('羊皮纸卷（物品）', 'placeholder://item/item_medieval_manuscript.jpg', 'item', '中世纪的手抄本', 'Medieval manuscript, illuminated manuscript, medieval book, ornate handwritten book, realistic style, high quality, detailed manuscript, beautiful medieval manuscript with illustrations, European medieval document with decorative borders', '中世纪,书籍,物品', NULL, NOW(), NOW()),
('骑士盔甲（物品）', 'placeholder://item/item_medieval_armor.jpg', 'item', '骑士的盔甲', 'Medieval armor, knight armor, plate armor, full suit of armor, realistic style, high quality, detailed armor, ornate medieval plate armor, European medieval armor with detailed metalwork', '中世纪,盔甲,物品', NULL, NOW(), NOW()),
('城堡钥匙（物品）', 'placeholder://item/item_medieval_key.jpg', 'item', '打开城堡大门的钥匙', 'Medieval key, castle key, ornate iron key, large medieval key, realistic style, high quality, detailed key, elaborate medieval key, European medieval key with intricate design', '中世纪,钥匙,物品', NULL, NOW(), NOW()),
('鹅毛笔（物品）', 'placeholder://item/item_medieval_quill.jpg', 'item', '用于书写的鹅毛笔', 'Quill pen, medieval writing tool, feather pen, ornate quill, realistic style, high quality, detailed quill, elegant medieval writing instrument, European medieval quill with decorative holder', '中世纪,文具,物品', NULL, NOW(), NOW()),
('纹章（物品）', 'placeholder://item/item_medieval_coat_of_arms.jpg', 'item', '家族的纹章', 'Coat of arms, heraldic emblem, medieval family crest, ornate heraldic shield, realistic style, high quality, detailed emblem, elaborate medieval coat of arms, European medieval heraldic design with symbols and colors', '中世纪,纹章,物品', NULL, NOW(), NOW());

-- ========== 文艺复兴 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('油画（物品）', 'placeholder://item/item_renaissance_painting.jpg', 'item', '文艺复兴时期的油画作品', 'Renaissance painting, oil painting, classical art masterpiece, ornate framed painting, realistic style, high quality, detailed painting, beautiful Renaissance artwork, European Renaissance painting with detailed brushwork', '文艺复兴,油画,物品', NULL, NOW(), NOW()),
('雕塑（物品）', 'placeholder://item/item_renaissance_sculpture.jpg', 'item', '精美的雕塑作品', 'Renaissance sculpture, marble sculpture, classical statue, ornate marble statue, realistic style, high quality, detailed sculpture, elegant Renaissance sculpture, European Renaissance art with detailed craftsmanship', '文艺复兴,雕塑,物品', NULL, NOW(), NOW()),
('天文仪器（物品）', 'placeholder://item/item_renaissance_astrolabe.jpg', 'item', '观测天体的仪器', 'Astrolabe, Renaissance astronomical instrument, ornate brass astrolabe, classical scientific instrument, realistic style, high quality, detailed instrument, elaborate Renaissance astrolabe, European Renaissance scientific tool with intricate engravings', '文艺复兴,仪器,物品', NULL, NOW(), NOW()),
('手稿（物品）', 'placeholder://item/item_renaissance_manuscript.jpg', 'item', '艺术家的手稿', 'Renaissance manuscript, artist sketchbook, classical notebook, ornate handwritten book, realistic style, high quality, detailed manuscript, beautiful Renaissance sketchbook, European Renaissance document with drawings and notes', '文艺复兴,手稿,物品', NULL, NOW(), NOW()),
('指南针（物品）', 'placeholder://item/item_renaissance_compass.jpg', 'item', '用于导航的指南针', 'Compass, Renaissance compass, ornate brass compass, classical navigation tool, realistic style, high quality, detailed compass, elaborate Renaissance compass, European Renaissance navigational instrument with decorative design', '文艺复兴,指南针,物品', NULL, NOW(), NOW()),
('羽毛笔（物品）', 'placeholder://item/item_renaissance_pen.jpg', 'item', '精致的羽毛笔', 'Quill pen, Renaissance writing tool, ornate feather pen, elegant writing instrument, realistic style, high quality, detailed pen, beautiful Renaissance quill, European Renaissance writing tool with decorative holder', '文艺复兴,文具,物品', NULL, NOW(), NOW()),
('时钟（物品）', 'placeholder://item/item_renaissance_clock.jpg', 'item', '精美的机械时钟', 'Renaissance clock, mechanical clock, ornate wall clock, classical timepiece, realistic style, high quality, detailed clock, elaborate Renaissance clock, European Renaissance timepiece with intricate mechanism', '文艺复兴,时钟,物品', NULL, NOW(), NOW()),
('书籍（物品）', 'placeholder://item/item_renaissance_book.jpg', 'item', '精美的书籍', 'Renaissance book, ornate leather-bound book, classical tome, decorated book cover, realistic style, high quality, detailed book, beautiful Renaissance book, European Renaissance book with ornate binding and illustrations', '文艺复兴,书籍,物品', NULL, NOW(), NOW());

-- ========== 工业革命 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('蒸汽机（物品）', 'placeholder://item/item_industrial_steam_engine.jpg', 'item', '驱动工业革命的蒸汽机', 'Steam engine, industrial revolution steam engine, mechanical engine, ornate industrial machinery, realistic style, high quality, detailed engine, elaborate steam-powered engine, Industrial Revolution machinery with pipes and gears', '工业革命,蒸汽机,物品', NULL, NOW(), NOW()),
('齿轮装置（物品）', 'placeholder://item/item_industrial_gear.jpg', 'item', '机械装置的齿轮', 'Industrial gear, mechanical gear, factory machinery gear, iron gear mechanism, realistic style, high quality, detailed gear, ornate industrial gear, Industrial Revolution mechanical component with detailed teeth', '工业革命,齿轮,物品', NULL, NOW(), NOW()),
('火车（物品）', 'placeholder://item/item_industrial_train.jpg', 'item', '蒸汽火车', 'Steam locomotive, industrial revolution train, steam-powered train, ornate railway engine, realistic style, high quality, detailed locomotive, elaborate steam train, Industrial Revolution transportation with smoke and steam', '工业革命,火车,物品', NULL, NOW(), NOW()),
('怀表（物品）', 'placeholder://item/item_industrial_pocket_watch.jpg', 'item', '精确的机械怀表', 'Pocket watch, industrial revolution timepiece, mechanical watch, ornate pocket watch, realistic style, high quality, detailed watch, elaborate mechanical watch, Industrial Revolution timepiece with visible gears', '工业革命,怀表,物品', NULL, NOW(), NOW()),
('工厂（物品）', 'placeholder://item/item_industrial_factory.jpg', 'item', '工业化的工厂', 'Factory building, industrial revolution factory, manufacturing plant, brick factory with chimneys, realistic style, high quality, detailed building, elaborate industrial factory, Industrial Revolution factory with smoke stacks', '工业革命,工厂,物品', NULL, NOW(), NOW()),
('织布机（物品）', 'placeholder://item/item_industrial_loom.jpg', 'item', '机械织布机', 'Mechanical loom, industrial revolution textile machine, powered loom, ornate weaving machine, realistic style, high quality, detailed loom, elaborate textile machinery, Industrial Revolution weaving machine with mechanical parts', '工业革命,织布机,物品', NULL, NOW(), NOW()),
('煤矿（物品）', 'placeholder://item/item_industrial_coal.jpg', 'item', '工业用的煤矿', 'Coal, industrial fuel, coal chunks, black coal material, realistic style, high quality, detailed coal, raw coal resource, Industrial Revolution fuel source with mineral texture', '工业革命,煤矿,物品', NULL, NOW(), NOW()),
('钢铁（物品）', 'placeholder://item/item_industrial_steel.jpg', 'item', '工业生产的钢铁', 'Steel, industrial metal, forged steel, iron and steel material, realistic style, high quality, detailed metal, processed industrial steel, Industrial Revolution material with metallic sheen', '工业革命,钢铁,物品', NULL, NOW(), NOW());

