-- 第二阶段：为中国古代历史场景的物品创建资源记录（包含AI图片生成提示词）
-- 场景：三国时代、秦王朝、唐朝盛世、宋朝文雅、明朝江湖

SET NAMES utf8mb4;

-- ========== 三国时代 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('青龙偃月刀（物品）', 'placeholder://item/item_three_kingdoms_green_dragon.jpg', 'item', '关羽的青龙偃月刀，重八十二斤', 'Green Dragon Crescent Blade, Guan Yu weapon, ancient Chinese weapon, heavy blade, Three Kingdoms weapon, realistic style, high quality, detailed weapon design, legendary weapon appearance', '三国,武器,物品', NULL, NOW(), NOW()),
('丈八蛇矛（物品）', 'placeholder://item/item_three_kingdoms_snake_spear.jpg', 'item', '张飞的丈八蛇矛', 'Zhang Fei Snake Spear, Eight Zhang Snake Spear, ancient Chinese spear, Three Kingdoms weapon, realistic style, high quality, detailed spear design, powerful weapon appearance', '三国,武器,物品', NULL, NOW(), NOW()),
('赤兔马（物品）', 'placeholder://item/item_three_kingdoms_red_hare.jpg', 'item', '日行千里的赤兔马', 'Red Hare Horse, legendary horse, fast horse, Three Kingdoms mount, realistic style, high quality, detailed horse, majestic horse appearance, legendary steed', '三国,坐骑,物品', NULL, NOW(), NOW()),
('羽扇（物品）', 'placeholder://item/item_three_kingdoms_feather_fan.jpg', 'item', '诸葛亮的羽扇', 'Zhuge Liang feather fan, strategy fan, ancient Chinese fan, Three Kingdoms item, realistic style, high quality, detailed fan design, elegant feather fan appearance', '三国,物品,物品', NULL, NOW(), NOW()),
('兵符（物品）', 'placeholder://item/item_three_kingdoms_army_token.jpg', 'item', '调动军队的兵符', 'Army token, military command token, ancient Chinese military token, Three Kingdoms military item, realistic style, high quality, detailed token, official military token design', '三国,兵符,物品', NULL, NOW(), NOW()),
('玉玺（物品）', 'placeholder://item/item_three_kingdoms_seal.jpg', 'item', '传国玉玺', 'Imperial Seal, jade seal, national treasure, Three Kingdoms treasure, realistic style, high quality, detailed seal, precious jade seal, royal seal appearance', '三国,玉玺,物品', NULL, NOW(), NOW()),
('箭矢（物品）', 'placeholder://item/item_three_kingdoms_arrow.jpg', 'item', '作战用的箭矢', 'Arrow, ancient arrow, military arrow, Three Kingdoms weapon, realistic style, high quality, detailed arrow, traditional arrow design, combat arrow appearance', '三国,武器,物品', NULL, NOW(), NOW()),
('书信（物品）', 'placeholder://item/item_three_kingdoms_letter.jpg', 'item', '传递军情的密信', 'Military letter, secret letter, military intelligence letter, Three Kingdoms document, realistic style, high quality, detailed letter, ancient letter format, sealed letter appearance', '三国,信件,物品', NULL, NOW(), NOW());

-- ========== 秦王朝 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('秦剑（物品）', 'placeholder://item/item_qin_sword.jpg', 'item', '秦军使用的青铜剑', 'Qin Dynasty bronze sword, ancient Chinese sword, Qin army weapon, bronze weapon, realistic style, high quality, detailed sword, traditional bronze sword design, historical weapon appearance', '秦朝,武器,物品', NULL, NOW(), NOW()),
('兵符（物品）', 'placeholder://item/item_qin_army_token.jpg', 'item', '调动军队的虎符', 'Tiger token, Qin Dynasty military token, army command token, ancient military token, realistic style, high quality, detailed token, bronze tiger token design, official military token', '秦朝,兵符,物品', NULL, NOW(), NOW()),
('竹简（物品）', 'placeholder://item/item_qin_bamboo.jpg', 'item', '记录文字的竹简', 'Bamboo slip, ancient writing material, Qin Dynasty document, traditional writing material, realistic style, high quality, detailed bamboo slip, ancient document format, historical writing material', '秦朝,文字,物品', NULL, NOW(), NOW()),
('秦半两（物品）', 'placeholder://item/item_qin_coin.jpg', 'item', '秦朝的统一货币', 'Qin Ban Liang coin, Qin Dynasty currency, ancient Chinese coin, unified currency, realistic style, high quality, detailed coin, historical coin design, ancient bronze coin', '秦朝,货币,物品', NULL, NOW(), NOW()),
('诏书（物品）', 'placeholder://item/item_qin_edict.jpg', 'item', '皇帝颁布的诏书', 'Imperial edict, Qin emperor decree, official imperial document, ancient Chinese edict, realistic style, high quality, detailed edict, royal document format, official imperial decree', '秦朝,诏书,物品', NULL, NOW(), NOW()),
('和氏璧（物品）', 'placeholder://item/item_qin_jade.jpg', 'item', '传世美玉和氏璧', 'He Shi Bi jade, legendary jade, precious jade artifact, Qin Dynasty treasure, realistic style, high quality, detailed jade, priceless jade piece, legendary treasure appearance', '秦朝,美玉,物品', NULL, NOW(), NOW()),
('弓弩（物品）', 'placeholder://item/item_qin_crossbow.jpg', 'item', '秦军的强弩', 'Qin crossbow, powerful crossbow, Qin army crossbow, ancient Chinese crossbow, realistic style, high quality, detailed crossbow, military crossbow design, powerful weapon appearance', '秦朝,武器,物品', NULL, NOW(), NOW()),
('秦砖（物品）', 'placeholder://item/item_qin_brick.jpg', 'item', '修建长城用的秦砖', 'Qin brick, Great Wall brick, construction material, Qin Dynasty brick, realistic style, high quality, detailed brick, historical brick, ancient construction material', '秦朝,建筑,物品', NULL, NOW(), NOW());

-- ========== 唐朝盛世 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('唐诗（物品）', 'placeholder://item/item_tang_poetry.jpg', 'item', '著名诗人的诗集', 'Tang poetry collection, famous poet collection, Tang Dynasty poetry book, classical Chinese poetry, realistic style, high quality, detailed poetry book, elegant book design, traditional poetry collection', '唐朝,诗歌,物品', NULL, NOW(), NOW()),
('丝绸（物品）', 'placeholder://item/item_tang_silk.jpg', 'item', '精美的丝绸', 'Silk fabric, Tang Dynasty silk, beautiful silk, Chinese silk, realistic style, high quality, detailed silk, luxurious silk fabric, elegant silk appearance', '唐朝,丝绸,物品', NULL, NOW(), NOW()),
('陶瓷（物品）', 'placeholder://item/item_tang_ceramic.jpg', 'item', '精美的陶瓷制品', 'Tang Dynasty ceramic, fine porcelain, Tang ceramic art, Chinese ceramic, realistic style, high quality, detailed ceramic, elegant ceramic design, traditional porcelain appearance', '唐朝,陶瓷,物品', NULL, NOW(), NOW()),
('官印（物品）', 'placeholder://item/item_tang_seal.jpg', 'item', '官员的印章', 'Official seal, Tang Dynasty official seal, government seal, ancient Chinese seal, realistic style, high quality, detailed seal, official seal design, traditional seal format', '唐朝,官印,物品', NULL, NOW(), NOW()),
('茶叶（物品）', 'placeholder://item/item_tang_tea.jpg', 'item', '上好的茶叶', 'Tang Dynasty tea, fine tea leaves, Chinese tea, premium tea, realistic style, high quality, detailed tea, traditional tea packaging, elegant tea appearance', '唐朝,茶叶,物品', NULL, NOW(), NOW()),
('扇子（物品）', 'placeholder://item/item_tang_fan.jpg', 'item', '文人雅士用的折扇', 'Folding fan, Tang Dynasty fan, scholar fan, elegant fan, realistic style, high quality, detailed fan, traditional Chinese fan, elegant fan design', '唐朝,扇子,物品', NULL, NOW(), NOW()),
('玉佩（物品）', 'placeholder://item/item_tang_jade.jpg', 'item', '精美的玉佩', 'Jade pendant, Tang Dynasty jade, fine jade ornament, Chinese jade, realistic style, high quality, detailed jade pendant, elegant jade design, precious jade appearance', '唐朝,玉佩,物品', NULL, NOW(), NOW()),
('文房四宝（物品）', 'placeholder://item/item_tang_stationery.jpg', 'item', '笔墨纸砚', 'Four Treasures of Study, brush ink paper inkstone, Tang Dynasty stationery, Chinese calligraphy tools, realistic style, high quality, detailed stationery set, traditional writing tools, elegant stationery appearance', '唐朝,文具,物品', NULL, NOW(), NOW());

-- ========== 宋朝文雅 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('宋词（物品）', 'placeholder://item/item_song_ci.jpg', 'item', '著名词人的词集', 'Song Ci poetry collection, famous Ci poet collection, Song Dynasty poetry book, classical Chinese Ci poetry, realistic style, high quality, detailed poetry book, elegant book design, traditional Ci collection', '宋朝,词,物品', NULL, NOW(), NOW()),
('茶具（物品）', 'placeholder://item/item_song_tea_set.jpg', 'item', '精美的茶具', 'Tea set, Song Dynasty tea set, fine tea ware, Chinese tea set, realistic style, high quality, detailed tea set, elegant tea ware design, traditional tea set appearance', '宋朝,茶具,物品', NULL, NOW(), NOW()),
('字画（物品）', 'placeholder://item/item_song_painting.jpg', 'item', '名家的字画作品', 'Calligraphy and painting, Song Dynasty artwork, famous artist work, Chinese calligraphy painting, realistic style, high quality, detailed artwork, elegant painting design, traditional art appearance', '宋朝,字画,物品', NULL, NOW(), NOW()),
('瓷器（物品）', 'placeholder://item/item_song_porcelain.jpg', 'item', '精美的瓷器', 'Song Dynasty porcelain, fine porcelain, Song ceramic art, Chinese porcelain, realistic style, high quality, detailed porcelain, elegant porcelain design, traditional ceramic appearance', '宋朝,瓷器,物品', NULL, NOW(), NOW()),
('扇子（物品）', 'placeholder://item/item_song_fan.jpg', 'item', '文人用的折扇', 'Folding fan, Song Dynasty fan, scholar fan, elegant fan, realistic style, high quality, detailed fan, traditional Chinese fan, elegant fan design', '宋朝,扇子,物品', NULL, NOW(), NOW()),
('文房用品（物品）', 'placeholder://item/item_song_stationery.jpg', 'item', '精致的文房用品', 'Stationery, Song Dynasty stationery, fine writing tools, Chinese stationery, realistic style, high quality, detailed stationery, elegant writing tools, traditional stationery appearance', '宋朝,文具,物品', NULL, NOW(), NOW()),
('茶叶（物品）', 'placeholder://item/item_song_tea.jpg', 'item', '上好的茶叶', 'Song Dynasty tea, fine tea leaves, Chinese tea, premium tea, realistic style, high quality, detailed tea, traditional tea packaging, elegant tea appearance', '宋朝,茶叶,物品', NULL, NOW(), NOW()),
('官帽（物品）', 'placeholder://item/item_song_official_hat.jpg', 'item', '官员的帽子', 'Official hat, Song Dynasty official hat, government official hat, ancient Chinese hat, realistic style, high quality, detailed hat, official hat design, traditional hat format', '宋朝,官帽,物品', NULL, NOW(), NOW());

-- ========== 明朝江湖 - 物品资源 ==========
INSERT INTO `system_resources` (`name`, `url`, `category`, `description`, `prompt`, `tags`, `created_by_admin_id`, `created_at`, `updated_at`) VALUES
('长剑（物品）', 'placeholder://item/item_ming_sword.jpg', 'item', '武林人士使用的长剑', 'Long sword, martial artist sword, Ming Dynasty sword, wuxia weapon, realistic style, high quality, detailed sword, traditional Chinese sword, elegant sword design', '明朝,武器,物品', NULL, NOW(), NOW()),
('武功秘籍（物品）', 'placeholder://item/item_ming_secret_book.jpg', 'item', '记载高深武功的秘籍', 'Martial arts secret book, kung fu manual, martial technique book, Ming Dynasty manual, realistic style, high quality, detailed book, ancient martial arts book, traditional manual format', '明朝,秘籍,物品', NULL, NOW(), NOW()),
('令牌（物品）', 'placeholder://item/item_ming_token.jpg', 'item', '江湖门派的令牌', 'Sect token, martial arts sect token, jianghu token, Ming Dynasty token, realistic style, high quality, detailed token, sect identification token, traditional token design', '明朝,令牌,物品', NULL, NOW(), NOW()),
('暗器（物品）', 'placeholder://item/item_ming_dart.jpg', 'item', '用于防身的暗器', 'Hidden weapon, dart, concealed weapon, Ming Dynasty weapon, realistic style, high quality, detailed dart, traditional hidden weapon, small weapon design', '明朝,武器,物品', NULL, NOW(), NOW()),
('解药（物品）', 'placeholder://item/item_ming_antidote.jpg', 'item', '解各种毒的解药', 'Antidote, poison antidote, medicine bottle, Ming Dynasty medicine, realistic style, high quality, detailed medicine, traditional medicine bottle, ancient medicine appearance', '明朝,药品,物品', NULL, NOW(), NOW()),
('银两（物品）', 'placeholder://item/item_ming_silver.jpg', 'item', '江湖通用的银两', 'Silver ingot, currency, silver coin, Ming Dynasty currency, realistic style, high quality, detailed silver, traditional currency, ancient silver coin design', '明朝,货币,物品', NULL, NOW(), NOW()),
('地图（物品）', 'placeholder://item/item_ming_map.jpg', 'item', '江湖路线图或藏宝图', 'Treasure map, jianghu map, route map, Ming Dynasty map, realistic style, high quality, detailed map, ancient map design, mysterious map appearance', '明朝,地图,物品', NULL, NOW(), NOW()),
('玉佩信物（物品）', 'placeholder://item/item_ming_jade_token.jpg', 'item', '作为信物的玉佩', 'Jade token, jade keepsake, identification jade, Ming Dynasty jade, realistic style, high quality, detailed jade, traditional jade token, elegant jade design', '明朝,信物,物品', NULL, NOW(), NOW());



